### ISSUE TITLE
browser.refresh() not working

### ISSUE THREAD

**Issue by niveinii** [SAP/ui5-uiveri5#104]
Hey,

After trying to get the page to refresh with browser.refresh() I get an error 
INFO: Expectation FAILED: Failed: Waiting for auth page to fully load. Step: redirect to login page.
The refresh is suppose to be committed after the first loading to a page with credentials. (entrance works fine). Please your advise.

Thanks,
Niv

**Comment by maximnaidenov** [comment]
UIVeri5 is intended for testing UI5 Apps. And UI5 apps are SPA that are not supposed to do page refresh/reload/redirects.
But what you describe does not seem to look related to page refresh but to authentication configuration. Can you please attach a debug log ( -v on command-line )

**Comment by vobu** [comment]
not trying to argue SPA, but a valid use-case for `browser.refresh()` might be any kind of testing `localStorage` handling in UI5 apps or even testing PWAs...

**Comment by niveinii** [comment]
[browser.refresh error.txt](https://github.com/SAP/ui5-uiveri5/files/3525453/browser.refresh.error.txt)

Attached the doc (censored credentials but they work fine).

**Comment by maximnaidenov** [comment]
@vobu For valid use-cases we have a way to synchronize with UI5 runtime after refresh/redirect: https://github.com/SAP/ui5-uiveri5/blob/master/docs/usage/browser.md

**Comment by niveinii** [comment]
Hey,
we've tried what you have offered.
The problem we face is that we need to do refresh for performance testing.

It seems that in fiori launchpad sites, when we try to refresh with uiveri5 it throws an error saying:
> INFO: Expectation FAILED: Failed: Waiting for auth page to fully load. Step: redirect to login page.

We tried also to add 'browser.loadUI5Dependencies()' after the refresh and it doesn't help (also in the browser.get()).

Thanks,
Niv

**Comment by maximnaidenov** [comment]
@niveinii The logs show the following error: 
INFO: Expectation FAILED: Failed: Waiting for auth page to fully load. Step: redirect to login page
Wait timed out after 80004ms
This means that the authenticator module could not validate that the login page is loaded. The login page seems standard, can you please attach this screenshot: 
DEBUG: Screenshot created "target\report\screenshots\masterdetail-click-app3_4_fail_2019-08-21T13-10-38.png"
?

**Comment by maximnaidenov** [comment]
This log shows some modifications to uiveri5 and/or some strange stuff: 
[16:09:17] W/element - more than one element found for locator By(xpath, //*[contains(text(),'App3')]) - the first result will be used
So what exactly is the scenario, can you please attach the spec and conf files ?

**Comment by niveinii** [comment]
[browserError.zip](https://github.com/SAP/ui5-uiveri5/files/3528972/browserError.zip)

all files attached. Right now the scenario is open site with credentials, click one of the tiles (we chose tile App3) and then refresh.

**Comment by maximnaidenov** [comment]
Hi Niv,
can you please provide a user/pass so I could reproduce the error ?. Also, what exactly do you expect to happen after the browser.refresh() as last statement of the test ? there are no further assertions or interactions ?

**Comment by niveinii** [comment]
Hey Maxim,

You can enter your own credentials (sap email and pass), should work fine.
I did not finish to build the scenario but the final result should be a loop that refreshes the page with a timestamp that measures the time for the site to be visually complete (I will catch the final element and wait for it to be load).

If you have any problems with site access, please let me know.

Thanks!
Niv

**Comment by maximnaidenov** [comment]
Hi Niv,
I checked this, the error shows we have some strange messup of angular stuff back, over our overridings. If you use the webdriver API like this, it works fine:

```
it('click app3', () => {
        tile.clickByName('App3');
        expect(element(by.control({controlType:'sap.m.Title'})).asControl().getProperty("text")).toBe('Title');

        browser.driver.navigate().refresh();
        browser.loadUI5Dependencies()
        expect(element(by.control({controlType:'sap.m.Title'})).asControl().getProperty("text")).toBe('Title');
    });
```

**Comment by niveinii** [comment]
Thanks Maxim, this worked!

**Comment by niveinii** [comment]
Hey Maxim,

In my scenario the refresh is key, and I've noticed that `browser.loadUI5Dependencies()` delays the refresh in several seconds. Is there a way to load the UI5 dependencies just once?

Thanks,
Niv
