### ISSUE TITLE
Error after switching to a new tab: uiveri5 is not defined

### ISSUE THREAD

**Issue by NIBOSAP** [SAP/ui5-uiveri5#105]
### Description

After clicking on a button to open a document in a new tab, the uiveri5 is not defined.

A workaround could be user `browser.refresh()`on the new tab.

### Error

```
INFO: Expectation FAILED: Failed: javascript error: uiveri5 is not definedReferenceError: uiveri5 is not defined
    at findByControl (<anonymous>:455:5)
    at <anonymous>:479:6
    at callFunction (<anonymous>:442:36)
    at <anonymous>:453:23
    at <anonymous>:454:3
  (Session info: chrome=76.0.3809.100)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Mac OS X 10.14.6 x86_64)
```

**Comment by maximnaidenov** [comment]
UIVeri5 is intended for testing UI5 apps and UI5 apps are SPA. They are not supposed to open new pages, do redirects/refresh/reloads. 
So there is no (standard) way to interact with the new tab, additionally most likely this document is not a UI5 app so no meaning in using UIVeri5 for this. 
If you need this so much, you need to switch to webdriverjs (browser.driver API).

**Comment by NIBOSAP** [comment]
Thanks
