### ISSUE TITLE
problem in calling a child element

### ISSUE THREAD

**Issue by niveinii** [SAP/ui5-uiveri5#112]
Hey,

I am trying to access a child element in the follow scenario:
1. enter with credentials
https://testflp-lkgtestcontp-testcontent-ar.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
2. press the me area button (top right)
3.press "edit home page"
4. press the "x" button on demoTile (delete it)

I have issues with finiding the "x" that belongs to the "demoTile" with the following ways:
1. element(by.jq('.sapUshellTile:has(\'.sapMText:contains(\"demoTile\")\')')).element(by.control({controlType: "sap.ui.core.Icon", properties:{src:"sap-icon://decline"}}));
2.
element(by.control({controlType: "sap.ushell.ui.launchpad.Tile",descendant: {controlType: "sap.m.Text", properties: {text: "demoTile"}}})).element(by.control({controlType: "sap.ui.core.Icon"}));
3.
element(by.control({controlType: "sap.ushell.ui.launchpad.Tile"})).element(by.control({controlType: "sap.ui.core.Icon"}));

Always with the same error No element found using locator: "insertFirstLocatorHere.element"by.control({"controlType":"sap.ui.core.Icon","properties":{"src":"sap-icon://decline"}}) meaning there is something wrong with the child search.(classically the child)

Please your advise.

Many Thanks,
Niv

**Comment by tsaleksandrova** [comment]
Hi Niv,
The selector {controlType: "sap.ui.core.Icon", properties:{src:"sap-icon://decline"}} by itself finds 19 controls as expected., so probably the parent is not correct.
Options 2 and 3. in you list find 25 parents, the first one of which doesn't have a decline icon.
And to use the descendant matcher, the app needs the latest ui5 version, which is still in progress. 
One idea I have is, you can find the tile using bindingPath, and then use it as an ancestor to the Icon.
(e.g.: {
"controlType":"sap.ushell.ui.launchpad.Tile",
"viewName":"sap.ushell.components.homepage.DashboardContent",
"bindingPath":{"path":"/groups/1/tiles/0","propertyPath":"long"}})

Regards,
Tsvetelina

**Comment by niveinii** [comment]
Hey,

> The selector {controlType: "sap.ui.core.Icon", properties:{src:"sap-icon://decline"}} by itself finds 19 controls as expected., so probably the parent is not correct.

The parent is o.k ,you can try element(by.jq('.sapUshellTile:has('.sapMText:contains("demoTile")')'))
from what I understand, after I insert the part .element(by.control({controlType: "sap.ui.core.Icon", properties:{src:"sap-icon://decline"}})); It should look for the controltype with the properties in the parent element, which it does not (the parent has 2 Icons in it). Could you please advise?

Thanks,
Niv
