### ISSUE TITLE
Report - Need to open each suite to check overall status

### ISSUE THREAD

**Issue by ThomasMarz** [SAP/ui5-uiveri5#113]
Hello UIVeri5  Team,

in the report html generated after test execution you can select the different suites on top of the screen to check the suite status:

![image](https://user-images.githubusercontent.com/13033347/64517131-03d84580-d2f0-11e9-98c0-f0d2dfc1b8e7.png)

but there is no way to easily understand the overall status. E.g. have all suites been successfull or are there some failing? Can you output the suite status on the link on top of the screen?

regards Thomas

**Comment by hmanchev** [comment]
Hello Thomas,

Current version of screenshot reporter does not support display of statuses of all suites. You should click on each suite to get it's details.

For the overall status you can check for example the output in the console - it will finish with summary of what is executed and their statuses. 

We will discuss and evaluate in the team whether such status can fit in the idea and purpose of the screenshot report.

Best Regards,
Hristo

**Comment by maximnaidenov** [comment]
Hi Thomas,
actually the idea of this report is to check it in case of error, no much sense to check a successfully passed test. And you already have the overall status of the execution in the CI server/pipeline status.
