### ISSUE TITLE
StaleElementReferenceError: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by vaibhavhirani** [SAP/ui5-uiveri5#122]
Hi, we are writing uiveri5 tests on a Fiori application.
List Report has rows where each row has 4 mdc fields containing title, label, email and mobile number.
We were trying to fetch value of each email field by running a loop in rows and compare the value returned by it to passed parameter. But it ran for number of times but after a while It started throwing saying " StaleElementReferenceError: stale element reference: element is not attached to the page document ".
How can we fix this problem ?

**Comment by maximnaidenov** [comment]
Hi,
this is the classical problem with StaleElement in selenium. The reason usually is that you not only inspect the elements but interact with them. Like clicking a link inside a loop executed inside the promise.
The solution is to use a good control locator (bindingPath, ancestor, descendant) and interact with the element in a subsequent statement (so interact statement is able to synchronize with ui5 runtime).

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov , thanks for the information. I ran the same piece of code again and now it worked fine and didn't throw any error for now but I'm not sure whether It will show the same behaviour. 
It is not consistent. Can you let me know if we can achieve the consistent behaviour with the given code as sometimes it is working and not working without any code change ?

**Comment by maximnaidenov** [comment]
As explained, this is bad practice tht depends on "happy" timing and there is no chance to make it run reliably. You will always have this problem sporadically till you do it the right way as I explained. This is a classical problem  with selenium and the warning not to interact inside the loop is explicitly mentioned in selenium docs.
