### ISSUE TITLE
IDP authorization is failed with the latest version v1.41.0

### ISSUE THREAD

**Issue by 549393092** [SAP/ui5-uiveri5#126]
Dear,

When upgrade UIVeri5 from v1.38.0 to v1.41.0, IDP authorization is failed.
This is IDP authorization configuration.
https://github.com/SAP/ui5-uiveri5/blob/master/e2e/scenario/formauth_idp.conf.js
When test it locally, the chrome will open and redirect to the IDP page, but it can't fill username and password and it will hang out on this page until timeout.

But it works on v.1.38.0, below is the log for v.1.38.0
===========================>
INFO: @ui5/uiveri5 v1.38.0
INFO: Resolving specs
(node:20340) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found correct binary locally: C:/chromedriverzz.exe
INFO: Executing 1 specs
[10:01:10] I/launcher - Running 1 instances of WebDriver

DevTools listening on ws://127.0.0.1:55953/devtools/browser/3163e152-8ec6-4b7a-883a-f455687d0175
INFO: Suite started: monitor-exception
INFO: Spec started: Step1: Test - Change Operation Actions -> In Process
INFO: Opening: https://xxx-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
INFO: UI5 Version: 1.71.1
INFO: UI5 Timestamp: 201910180748
INFO: Spec finished: Step1: Test - Change Operation Actions -> In Process with status: PASSED
......
[10:03:11] I/launcher - 0 instance(s) of WebDriver still running[10:03:11] I/launcher - chrome #01 passed
<===========================

Below is the log for v.1.41.0
===========================>
INFO: @ui5/uiveri5 v1.41.0
INFO: Resolving specs
(node:5408) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found correct binary locally: C:/chromedriverzz.exe
INFO: Executing 1 specs
[10:57:39] I/launcher - Running 1 instances of WebDriver

DevTools listening on ws://127.0.0.1:50032/devtools/browser/eafe5dfb-49a7-49a7-a31a-74717379e5cc
INFO: Suite started: monitor-exception
INFO: Spec started: Step1: Test - Change Operation Actions -> In Process
INFO: Opening: https://xxx-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
INFO: Expectation FAILED: Failed: Waiting for auth page to fully load. Step: redirect to default IDP login page
Wait timed out after 900001ms
INFO: Expectation FAILED: Failed: javascript error: uiveri5 is not definedReferenceError: uiveri5 is not defined
    at findByControl (eval at executeScript (:477:28), <anonymous>:4:5)
    at eval (eval at executeScript (:477:28), <anonymous>:28:6)
    at executeScript (<anonymous>:477:54)
    at <anonymous>:482:24
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: chrome=77.0.3865.75)
<===========================

Could you please have a look?

**Comment by maximnaidenov** [comment]
Hi, seems you are hurt by the changes in 1.40 related to IDP handling. Can you please provide debug logs with 1.41 and the real app URL. Please send me direct mail if you are concerned by exposing this information here.

**Comment by 549393092** [comment]
Hi,

Below are the log.
INFO: @ui5/uiveri5 v1.41.0
DEBUG: Config from command-line: {"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"conf":"C:\\Work\\DevOps\\V2Portal\\mmt-ui-app-monexceptions\\uiveri5\\confLocal.js"}
DEBUG: Loading default config from: C:\Work\DevOps\V2Portal\mmt-ui-app-monexceptions\uiveri5\confLocal.js
DEBUG: Loading profile config config from: ../conf/integration.profile.conf.js
DEBUG: Loading common profile config from: ../conf/profile.conf.js
DEBUG: Resolved runtime: {"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}
DEBUG: Config after resolving config file and profile: {"timeouts":{"waitForUI5Delta":200,"getPageTimeout":"500000","allScriptsTimeout":"550000","defaultTimeoutInterval":"600000","waitForUI5PollingInterval":400},"useClassicalWaitForUI5":false,"connection":"direct","connectionConfigs":{"direct":{"name":"./connection/directConnectionProvider","binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver.exe","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_win32.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"},"localPath":"C:/chromedriverzz.exe"},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"true","untar":"false","filename":"geckodriver.exe","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-win32.zip","latestVersionUrlRedirect":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}},"browserCapabilities":{"browser,chrome":{"android":{"*":{"deviceName":"android"}}},"firefox,ie,edge,safari,chrome,chromium":{"windows,mac,linux":{"*":{"remoteWebDriverOptions":{"maximized":true}}}},"chrome,chromium":{"*":{"*":{"chromeOptions":{"args":["disable-infobars"]}}}},"safari":{"mac":{"*":{"safaridriverOptions":{"addArguments":["--legacy"]}}}},"chromeMobileEmulation":{"*":{"*":{"browserName":"chrome","remoteWebDriverOptions":{"maximized":false,"scaling":{"x":4,"y":4}},"chromeOptions":{"mobileEmulation":{"deviceMetrics":{"width":360,"height":560,"pixelRatio":4}}}}}},"chromeHeadless":{"*":{"*":{"browserName":"chrome","chromeOptions":{"args":["--headless","--no-sandbox"]}}}}},"auth":{"sapcloud-form":{"user":"dl_5b90c569ecb21198e8000002@exchange.sap.corp","pass":"IBSOtech@2018!","idpSelector":"#saml-login-link"}},"authConfigs":{"plain":{"name":"./authenticator/plainAuthenticator"},"basic":{"name":"./authenticator/basicUrlAuthenticator"},"fiori-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#USERNAME_BLOCK input","passFieldSelector":"#PASSWORD_BLOCK input","logonButtonSelector":"#LOGIN_LINK"},"sapcloud-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit"}},"reporters":[{"name":"./reporter/consoleReporter"},{"name":"./reporter/screenshotReporter"}],"locators":[{"name":"./defaultLocators"}],"plugins":[],"matchers":[],"specResolver":"./resolver/localSpecResolver","pageLoading":{"wait":"3000"},"takeScreenshot":{"onExpectFailure":true,"onExpectSuccess":true,"onAction":true},"profile":"integration","baseUrl":"https://macov2-stage-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home","specs":"uiveri5\\*.spec.js","params":{"user":"dl_5b90c569ecb21198e8000002@exchange.sap.corp","pass":"IBSOtech@2018!","url":"https://macov2-stage-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home"},"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"conf":"C:\\Work\\DevOps\\V2Portal\\mmt-ui-app-monexceptions\\uiveri5\\confLocal.js","osTypeString":"win32","runtimes":[{"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}]}
DEBUG: Current working directory: C:\Work\DevOps\V2Portal\mmt-ui-app-monexceptions
DEBUG: Loading module: ./resolver/localSpecResolver with instance config: {}
INFO: Resolving specs
DEBUG: Resolving specs from: uiveri5\*.spec.js
DEBUG: Spec found, name: monitor-exception ,path: C:/Work/DevOps/V2Portal/mmt-ui-app-monexceptions/uiveri5/monitor-exception.spec.js ,url:https://macov2-stage-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
DEBUG: Loading module: ./connection/directConnectionProvider with instance config: {"binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver.exe","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_win32.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"},"localPath":"C:/chromedriverzz.exe"},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"true","untar":"false","filename":"geckodriver.exe","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-win32.zip","latestVersionUrlRedirect":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}
DEBUG: Setting getPageTimeout: 500000
DEBUG: Setting allScriptsTimeout: 550000
DEBUG: Setting defaultTimeoutInterval: 600000
DEBUG: Resolved protractor multiCapabilities from runtime: [{"browserName":"chrome","platform":"WINDOWS","chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"runtime":{"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}}]
DEBUG: Loading BDD-style page object factory
DEBUG: Setting up connection provider environment
(node:20692) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found correct binary locally: C:/chromedriverzz.exe
INFO: Executing 1 specs
[15:45:48] D/launcher - Running with --troubleshoot
[15:45:48] D/launcher - Protractor version: 5.3.2
[15:45:48] D/launcher - Your base url for tests is https://macov2-stage-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
[15:45:48] D/plugins - Plugin "Plugin #0" loaded.
[15:45:48] I/launcher - Running 1 instances of WebDriver
DEBUG: Starting local chromedriver with executable: C:/chromedriverzz.exe

DevTools listening on ws://127.0.0.1:59430/devtools/browser/7fdb25a8-26dd-42f1-9525-3bfb5c7713bb
[15:45:54] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_:
   Map {
     'acceptInsecureCerts' => false,
     'acceptSslCerts' => false,
     'applicationCacheEnabled' => false,
     'browserConnectionEnabled' => false,
     'browserName' => 'chrome',
     'chrome' => { chromedriverVersion:
        '76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})',
       userDataDir:
        'C:\\Users\\XXX\\AppData\\Local\\Temp\\scoped_dir19704_1784958844' },
     'cssSelectorsEnabled' => true,
     'databaseEnabled' => false,
     'goog:chromeOptions' => { debuggerAddress: 'localhost:59430' },
     'handlesAlerts' => true,
     'hasTouchScreen' => false,
     'javascriptEnabled' => true,
     'locationContextEnabled' => true,
     'mobileEmulationEnabled' => false,
     'nativeEvents' => true,
     'networkConnectionEnabled' => false,
     'pageLoadStrategy' => 'normal',
     'platform' => 'Windows NT',
     'proxy' => {},
     'rotatable' => false,
     'setWindowRect' => true,
     'strictFileInteractability' => false,
     'takesHeapSnapshot' => true,
     'takesScreenshot' => true,
     'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
     'unexpectedAlertBehaviour' => 'ignore',
     'version' => '77.0.3865.120',
     'webStorageEnabled' => true } }
[15:45:54] D/runner - Running with spec files C:\Work\DevOps\V2Portal\mmt-ui-app-monexceptions\uiveri5\monitor-exception.spec.js
DEBUG: Loading module: ./defaultLocators with instance config: {}
DEBUG: Registering default locators
DEBUG: Loading module: ./reporter/consoleReporter with instance config: {}
DEBUG: Loading module: ./reporter/screenshotReporter with instance config: {}
INFO: Suite started: monitor-exception
INFO: Spec started: Step1: Test - Change Operation Actions -> In Process
DEBUG: Runtime resolved from capabilities: {"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}
DEBUG: Maximizing browser window
DEBUG: Loading module: ./authenticator/formAuthenticator with instance config: {"userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit","user":"dl_5b90c569ecb21198e8000002@exchange.sap.corp","pass":"IBSOtech@2018!","idpSelector":"#saml-login-link"}
DEBUG: Execute async script: loadUI5Dependencies with params: {"waitForUI5Timeout":549800,"waitForUI5PollingInterval":400,"useClassicalWaitForUI5":false}
INFO: Opening: https://macov2-stage-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home

**Comment by 549393092** [comment]
Dear,

Could your please evaluate when will this issue be fixed?
Currently, our Jenkins server is using the latest UIVeri5 version that will abort the pipeline when using IDP login.
Thank you very much!

**Comment by maximnaidenov** [comment]
Hi,
The error message
INFO: Opening: https://xxx-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
INFO: Expectation FAILED: Failed: Waiting for auth page to fully load. Step: redirect to default IDP login page
Actually means that the element with "idpSelector":"#saml-login-link" is not found.  And actually this is correct because when I open https://xxx-dev.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home in my browser, I do not see IDP selection link. So I am wondering why did you configure this in your: C:\Work\DevOps\V2Portal\mmt-ui-app-monexceptions\uiveri5\confLocal.js ?
In 1.38 this works simply because we do not have IDP selection and so this property is simply ignored.

**Comment by 549393092** [comment]
Hi 
Yes, after delete the line "idpSelector":"#saml-login-link", it works.
Maybe the documentation should be updated.
https://github.com/SAP/ui5-uiveri5/blob/master/e2e/scenario/formauth_idp.conf.js
Thanks a lot for your help.

**Comment by maximnaidenov** [comment]
This is not documentation, this is a mock file, part of our test suite. Documentation is here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md
Please feel free to suggest any improvements that you find useful.
