### ISSUE TITLE
Pass arguments to cli to sepcify config file name

### ISSUE THREAD

**Issue by MichelMelhem** [SAP/ui5-uiveri5#131]
Hello,
I recently start to use ui veri5 to test my ui but i'm encountering a serious issue.
My config file does not meet the name  requirements "conf.js" but i couldn't find any args to the command ```ùiveri5``` that allow me to specfiy the name of my config file.
I hope you understand my issue.
Thank you,
Michel M

**Comment by maximnaidenov** [comment]
Hi Michael,
the conf.js is a default name, you could use any name and path for the conf file, just give it as the last argument. uiveri5 -h shows it.
