### ISSUE TITLE
Screenshot Reporter showing ID instead of header

### ISSUE THREAD

**Issue by Thottan** [SAP/ui5-uiveri5#134]
Hi,

We are writing e2e tests for a sapui5 application.
The Screenshot Reporter is enabled from the config file. 
The Report generated shows the ID of the tile instead of the header.

<img width="687" alt="ScreenshotReporter" src="https://user-images.githubusercontent.com/11848061/68180384-8a8c6480-ffb9-11e9-880d-f5c59fa136a2.PNG">

Is there some way to override this and provide the header name during report generation so as to make the report more readable?

**Comment by maximnaidenov** [comment]
Hi, this is the ID of the DOM element that you have selected and you send the click().  We have better reporting in case of error - it will show the selector (by.control(<selector>)) but at the level of screenshot report, this information is missing as it is resolved to DOM element.
Showing anything control-related here is very thicky - it will require reverse resolving of control and extracting some property (different for every control). The best that we could possibly implement is to show the locator used to find the element like in the error case.

**Comment by Thottan** [comment]
Hi, 
Is it possible to show the header instead of the ID if we pass the header while clicking, so that reverse resolving of control is not required but rather just use that name (whatever is provided in code) for creating the report?
This will enhance readability as to which tile or button is clicked.

**Comment by maximnaidenov** [comment]
We can't show "header" as we don't have this header in the test runtime. The header is a control in the browser runtime. Second, you want some property of the header, not the control itself and this will require revwerse resolving of the control from the dom element. 
What we can do is show the selector e.g. the content of the by.control('<control selector>') but this is a feature and will take some time.

**Comment by maximnaidenov** [comment]
I added this to our backlog, will update this ticket when ready.

**Comment by tsaleksandrova** [comment]
the locator will be available in the next uiveri5 version
