### ISSUE TITLE
How to run specs in different folder from conf.js

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#140]
Hi,

I have test cases in different folders and i want to run them from conf.js file. How can I specify the run? Protractor supports by passing them in array 
specs: ["automation/space/*","automation/group/*"]

How to achieve the above in uiveri5

**Comment by maximnaidenov** [comment]
Hi, we support the glob pattern so you can do specs: "somefolder/*.spec.js. Arrays are not supported yet.

**Comment by nipun0212** [comment]
Thanks, Maxim. Is array support in the pipeline?

**Comment by maximnaidenov** [comment]
We have a backlog but I cant' promise a deadline right now.

**Comment by tsaleksandrova** [comment]
Hi again,
Here is a solution we plan to merge: https://github.com/SAP/ui5-uiveri5/pull/149
If you're interested, you could try it out and see if it fits your needs
Feedback is appreciated!
