### ISSUE TITLE
navigate to a page in test code

### ISSUE THREAD

**Issue by jiawang1** [SAP/ui5-uiveri5#15]
Hi: 
according to your read me file, uiveri5 could load a page vai config.js
```code
exports.config = {
  profile: 'integration',

  baseUrl: 'https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/master-detail/webapp/test/mockServer.html',
};
```
but if I want to verify multiple pages, I can not configure several baseUrls in config.js. So I need load page in test script. I have tried protractor way:
```
 browser.get("https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/master-detail/webapp/test/mockServer.html");
```
but it will raise error since get method will verify angular.
then I try to use web driver API directly:
```
browser.driver.get("https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/master-detail/webapp/test/mockServer.html");
```
this also not work, it raise uiveri5 undefined error. So I debug your source code, then write code like this:
```
browser.driver
    .get(
      "https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/master-detail/webapp/test/mockServer.html"
    )
    .then(() => {
      return browser.loadUI5Dependencies();
    });
```
this time, it works. 
So I think method browser.get should be enhanced to get rid of angular check. Or if there is other way to load page in test script, please state in documents. thanks.

**Comment by maximnaidenov** [comment]
Hi,
actually we call this programatic authentication:
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md

**Comment by jiawang1** [comment]
hi
I just want to navigate from one page to another, after debug the code, I found this can work: 
```
return browser.testrunner.navigation.to('https://XXXXXXXX/', {auth:'plain'});
```

**Comment by maximnaidenov** [comment]
Closing as the issue seems to be solved
