### ISSUE TITLE
passing parameters in console not working

### ISSUE THREAD

**Issue by niveinii** [SAP/ui5-uiveri5#177]
Hey Maxim,

We are using the command line to pass in the tests we want to use in our jenkins job.
It seems like the parameters won't switch from false to true when using`--params.static_tile=true`
in the shell in order to switch it from false to true (used to work). Could you please help us resolve this?
you can try and use this command, and print the variable in the spec, you will see it is still false
`uiveri5 --params.user=<EMAIL> --params.pass=<PASSWORD> --baseUrl=https://testContentSaas-lkgtestcontentdonotdelete-testcontent-ar.cfapps.sap.hana.ondemand.com/cp.portal/site --config.takeScreenshot.onAction=true --params.static_tile=false ` (example)

Attached files.
[veri5.zip](https://github.com/SAP/ui5-uiveri5/files/4318984/veri5.zip)

**Comment by maximnaidenov** [comment]
Hi,
we will have a look and update you soon.

**Comment by niveinii** [comment]
small correction: use

`uiveri5 --params.user=<EMAIL> --params.pass=<PASSWORD> --baseUrl=https://testContentSaas-lkgtestcontentdonotdelete-testcontent-ar.cfapps.sap.hana.ondemand.com/cp.portal/site --config.takeScreenshot.onAction=true --params.static_tile=true`

you can put your own user and password, thanks!

**Comment by tsaleksandrova** [comment]
Hi, you're importing the config file and reading the data only from it. you should use
browser.testrunner.config.params  to access the merged values from console and config file

**Comment by niveinii** [comment]
Thanks!

I figured out it is something related to the naming of the parameter passing, as in protractor it is browser.params, wasn't sure how it is named in uiveri5. I think it could be great if you could document it as I did not find it in the documentation & it could be very helpfull.

Thanks again,
Niv

**Comment by maximnaidenov** [comment]
Hi, actually it is documented here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/parameters.md
Our approach is very similar to the protractor way but because we developed it independently (and earlier), we have a slightly different naming.
