### ISSUE TITLE
Veri5 chrome headless not working

### ISSUE THREAD

**Issue by nitaiaharoni1** [SAP/ui5-uiveri5#18]
Hey,
I'm trying to run my Veri5 test on a remote docker image.

When I'm not using the –headless flag, it crashes.
When I am using the –headless flag, it fails due to:
Expectation FAILED: Failed: loadUI5Dependencies: No UI5 on this page

(It happens when I try to run it localy too)
Can you please help me with this?

**Comment by maximnaidenov** [comment]
Hi Nitai,
We do not support '--headless' flag on cmd line if this is what you refer. As described here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/config.md you need to use '--browsers=chromeHeadless'. Can you please try it this way ?

**Comment by maximnaidenov** [comment]
Closing as seems to be a configuration issue.
