### ISSUE TITLE
Logging in after logging out

### ISSUE THREAD

**Issue by MayDruyan** [SAP/ui5-uiveri5#181]
Hi!
I am writing a test where I log in, make a few changes, then log out, log in then make sure the changes I made are still applied. 
I manage to log out, but I seem to have a problem when I try to login since this is not a UI5 page anymore. How do I login again?

Thank you!

**Comment by maximnaidenov** [comment]
Hi, you need to use programatic authentication. Set baseUrl to null and use browser.get(<url>,authObject). Then run your test steps, then logout and then again browser.get again with same or other user. Please see:  https://github.com/SAP/ui5-uiveri5/blob/master/docs/usage/browser.md
