### ISSUE TITLE
click() event is not being sent to sap.m.PlanningCalendar when there is CalendarAppointment

### ISSUE THREAD

**Issue by bgbonev** [SAP/ui5-uiveri5#184]
Hello,

I have a situation when click() is not working in sap.m.PlanningCalendar in case i have an overlapping sap.ui.unified.CalendarAppointment (see the screenshot). 
<img width="553" alt="calendar_issue" src="https://user-images.githubusercontent.com/63250500/78578233-e3e21380-7837-11ea-8a90-b24c135d10e2.png">
The following code works fine on Wednesday, but not on Friday! No event seems to be sent down the line when i use veri5.
```
function getCell(personIdx, dayOfTheWeek)
{   //day of the week is 0-6 (Monday-Sunday).

    return element(by.control( { 
        controlType : "PlanningCalendarRowTimeline", 
        id : new RegExp("__row0-__xmlview0--schedulePlanningCalendar-"+ personIdx + "-CalRow$"), 
        interaction: { idSuffix : "AppsInt" + dayOfTheWeek } }));
} 
var calendarDay = getCell(personIdx, day);
calendarDay.click(); 
```
Any ideas how to overcome this?

I'm currently using showEmptyIntervalHeaders = true to add additional elements to the calendar where i can click, but that's not really a solution as it differs from production code.

**Comment by maximnaidenov** [comment]
A basic assumption in every browser is that a user should not be able to click an element that is behind another element. The upper-most element will get the click . You can't do this manually and similarly, you cant do it with selenium. Selenium detects this condition and will throws a n error with descriptive exception that states which element will actually get the click. 
So do you have an error in your test?

**Comment by bgbonev** [comment]
It's not fully overlapped (you have the right half of the cell) and thus it's a valid scenario that works ok when i manually click it. I don't get any error, it "fails" silently as if it really tries to click it but the signal is lost somewhere in the middle.

**Comment by maximnaidenov** [comment]
Events do not disapear, very frequently they are sent but not handled and so "get lost" Can you please check carefully in DevTools where do you send the event and where is the handler. You send it to:
controlType : "PlanningCalendarRowTimeline", 
        id : new RegExp("__row0-__xmlview0--schedulePlanningCalendar-"+ personIdx + "-CalRow$"), 
        interaction: { idSuffix : "AppsInt" + dayOfTheWeek } }));
and this is a specific DOM element. Where is the event handler that you expect to be called ?

**Comment by malkoto1** [comment]
> 
> 
> Events do not disapear, very frequently they are sent but not handled and so "get lost" Can you please check carefully in DevTools where do you send the event and where is the handler. You send it to:
> controlType : "PlanningCalendarRowTimeline",
> id : new RegExp("__row0-__xmlview0--schedulePlanningCalendar-"+ personIdx + "-CalRow$"),
> interaction: { idSuffix : "AppsInt" + dayOfTheWeek } }));
> and this is a specific DOM element. Where is the event handler that you expect to be called ?

Hi, 

This is Rado from @bgbonev 's team.

We are binding to is "intervalSelect" event of the AppointmentCalendar control. What is happening is that our handler is not reached.

Do you assume that `controlType : "PlanningCalendarRowTimeline"` should be `controlType : "PlanningCalendar"`. 
If yes, why does it work when we don't have appointment overlapping?

**Comment by maximnaidenov** [comment]
I don't know why your handler is not called, this is outside of the scope of the testing tool. What I am interested to what DOM element you send the click and is it the correct one ?

**Comment by bgbonev** [comment]
In the given case (Friday):
`Execute 'click' on element with ID '__row0-__xmlview0--schedulePlanningCalendar-1-CalRow-AppsInt4'`

It's a "div" and I confirm that it is the correct element.

**Comment by maximnaidenov** [comment]
So what happens if you click on this element manually (find with DevTools - Inspector and click in the middle of the rectangle) ?

**Comment by bgbonev** [comment]
<img width="784" alt="calendar" src="https://user-images.githubusercontent.com/63250500/78672017-bdc87c00-78e8-11ea-8caa-1d7e44a783e2.png">
I cannot click exactly in the center (as it's been overlapped) but slightly on the right in that case. Is it possible that this could be the problem?

**Comment by maximnaidenov** [comment]
So we are back in the beginning - you have an element that is overwrapping another element and you wonder why you can't click on the below one ?

**Comment by bgbonev** [comment]
It's only PARTIALLY overlapped (half of it), unfortunately the geometrical center is overlapped.

**Comment by maximnaidenov** [comment]
In selenium there is no way to say which part of the element to click, you specify the element and up to my knowledge, it generates the click with coordinates in the geometrical center. The same is in uiveri5. Can you confirm by sending the click to the upper element

**Comment by bgbonev** [comment]
Click on the upper element works as expected, but bear in mind its center is on another coordinates.

Meanwhile we did an experiment by reducing the overlapping element so that it doesn't mess with the center, and it seems to be good and maybe in this case this will work for us. However, i believe that such workaround might not be feasible in many situations.

Thank you very much for helping us understand the issue! It's up to you to decide whether it's worth keeping the issue opened.

**Comment by maximnaidenov** [comment]
By design selenium "clicks" the center of an element and up to my knowledge, there is no way to change it. This behavior is an industry-standard and actually expected. There is the action API that supports mouseMove({x,y})  but its support is limited to some browsers (chrome, doesn't work in safari, IE, buggy in firefox).
