### ISSUE TITLE
sap.ui.unified.FileUploader - how to upload a file

### ISSUE THREAD

**Issue by alinva** [SAP/ui5-uiveri5#189]
Dear colleagues,

Could you please mention how to upload a file to FileUploader using uiveri5 ?

Thanks & Best regards,
Alina

**Comment by maximnaidenov** [comment]
Hi, UIVeri5 is webdriverjs + some UI5 helpers and so everything that works in webdrivejs works here also. Generally, the idea is to find the file input dom element and send the absolute name of the uploaded file. Webdriver will handle this and the file will be uploaded. Here is a snippet from some existing tests:

var docUploadInput = element(by.control({
   id : "fileUploader"
}));
 
action:
    iUploadDocument : function(sPath) {
        var absolutePath = path.resolve(__dirname, sPath);//(when files are saved in the some folder in the project itself)
        docUploadInput.sendKeys(absolutePath);
    },

in spec.js

When.onTheDocumentFormats.iUploadDocument(filePath);

**Comment by alinva** [comment]
Thanks!

**Comment by nuramon9999** [comment]
Hi there :)
I tried this, but sendKeys only goes into the input but is unable to type anything. When in the element I cannot type anything either. 
Could the input be disabled? If so, how to I reenable it.
Alternatively, I can change the value of the element. Then I can actually input something. But then I do not know how to submit the fileUploader.
Any advise on that? 
Best regards,
Pascal
