### ISSUE TITLE
Element was not loaded after login

### ISSUE THREAD

**Issue by MayDruyan** [SAP/ui5-uiveri5#190]
Hi,
I am writing a test for veri5 and having a bit of trouble with loading elements after logging out and then logging in again.
In order to make sure the element is loaded, I use browser.driver.wait() for the element, but after some time it returns timeout since the element is not loaded.
It seems that after I log out and log in, the elements are not fully loaded.
Can you please advise? If there are any logs required please let me know.
Thank you

**Comment by MayDruyan** [comment]
Is there any update?

**Comment by maximnaidenov** [comment]
Can you please provide the relevant fragment from your spec.js, the conf.js and some debug logs that should the problem ?

**Comment by MayDruyan** [comment]
Sorry nevermind :)
