### ISSUE TITLE
Incorrect error "Your application needs a newer version of UI5 to use control locators!"

### ISSUE THREAD

**Issue by ArnaudBuchholz** [SAP/ui5-uiveri5#193]
When running UIveri5 on some systems, we get the error :
`Your application needs a newer version of UI5 to use control locators!  Minimum versions supported: 1.52.12; 1.54.4; 1.55 and up.`
But the actual version of UI5 is 1.78.

**Comment by ArnaudBuchholz** [comment]
Submitted a fix https://github.com/SAP/ui5-uiveri5/pull/194

**Comment by maximnaidenov** [comment]
fixed in https://github.com/SAP/ui5-uiveri5/releases/tag/v1.43.0
Thanks for your contribution.
