### ISSUE TITLE
Timeout after authenticating with form authenticator

### ISSUE THREAD

**Issue by nathanss** [SAP/ui5-uiveri5#195]
Hello,

I am trying to use the `formAuthenticator` authenticator in my tests. The login form is the FLP login screen from Netweaver.

![image](https://user-images.githubusercontent.com/13437655/81189840-738cf600-8f8d-11ea-9dba-aab8e6434601.png)

Here's my configuration file:

```javascript
exports.config = {
  profile: "integration",
  specs: "./tests/**/*.spec.js",
  baseUrl: "<internal_server_link>/sap/bc/ui2/flp#Shell-home",
  timeouts: {
    getPageTimeout: "99000",
    allScriptsTimeout: "99000",
    defaultTimeoutInterval: "99000",
  },
  browsers: [
    {
      browserName: "firefox"
    }
  ],
  auth: {
    'sapcloud-form': {
      name: './authenticator/formAuthenticator',
      userFieldSelector: '#USERNAME_FIELD-inner',
      passFieldSelector: '#PASSWORD_FIELD-inner',
      logonButtonSelector: '#LOGIN_LINK',
      user: '${params.user}',
      pass: '${params.pass}'
    }
  }
};

```

After authentication, I run a simple test which navigates to an URL. This navigation works, but it seems the framework is waiting for something afterwards, and the tests timeout.

![image](https://user-images.githubusercontent.com/13437655/81190676-86ec9100-8f8e-11ea-8495-222cf657034b.png)

What could possibly be happening?

**Comment by Psidium** [comment]
The weird part is that the test passes when we remove the `auth: { ... }` from the config, and it hangs if the auth is there.

**Comment by maximnaidenov** [comment]
The screenshot shows double authentication, you know that with declarative auth (in conf.js) you don't need to do browser.get() right ?.

**Comment by Psidium** [comment]
In our product, we have more than 5 applications. How do we navigate between them without `browser.get`?

**Comment by maximnaidenov** [comment]
You either use declarative authentication for simple usecases OR you use browser.get and you disable the declarative authentication by setting baseUrl to null and removing the auth section from conf.js. You provide the same auth object as the second parameter of browser.get if you need to authenticate.
