### ISSUE TITLE
Error while getting the latest version number for chromedriver.exe, error: Error: connect ETIMEDOUT 172.217.160.80:443

### ISSUE THREAD

**Issue by ZhanJohnny** [SAP/ui5-uiveri5#216]
When i try to run uiveri5 , below error is pop.  My chorme is the latest version . Can i switch off this check ?

**Check for latest version of: chromedriver.exe
Error while getting the latest version number for chromedriver.exe, error: Error: connect ETIMEDOUT 172.217.160.80:443**

**Comment by maximnaidenov** [comment]
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md
