### ISSUE TITLE
No specs found even though conf.js is in place

### ISSUE THREAD

**Issue by malkoto1** [SAP/ui5-uiveri5#222]
Hi there, 

Using the latest version, 1.44.0 I am getting the following error: **Error: No specs found**

I have the conf.js in my root directory where I run "uiveri5" command. I tried giving the conf.js file explicitly, but I always get the same error.

Edit: It also happens with 1.43.0 and 1.42.2

**Comment by maximnaidenov** [comment]
Do you happen to have a dot as part of the path where your test resides ?

**Comment by malkoto1** [comment]
Nope. It is C:\Workspace\<project>\conf.js

**Comment by maximnaidenov** [comment]
this <project>, does it contain dots ?

**Comment by malkoto1** [comment]
No. Only dashes.

**Comment by maximnaidenov** [comment]
please provide debug log (-v)

**Comment by malkoto1** [comment]
DEBUG: Config from command-line: {"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"conf":"C:\\Workspace\\time-schedule-test-uiveri5\\conf.js"}
DEBUG: Loading default config from: C:\Workspace\\**project**\conf.js
DEBUG: Adding module with ID "undefined" and name "undefined"under key "browsers"
DEBUG: Loading config from: C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\conf\integration.profile.conf.js
DEBUG: Adding module with ID "undefined" and name "./reporter/screenshotReporter"under key "reporters"
DEBUG: Loading common profile config from: ..\conf\profile.conf.js
DEBUG: Adding module with ID "undefined" and name "./reporter/consoleReporter" under key "reporters"
DEBUG: Adding module with ID "undefined" and name "./locators/jqueryLocator"under key "locators"
DEBUG: Adding module with ID "undefined" and name "./locators/controlLocator"under key "locators"
DEBUG: Resolved runtime: {"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}
DEBUG: Config after resolving config file and profile: {"timeouts":{"waitForUI5Delta":200,"getPageTimeout":"30000","allScriptsTimeout":"31000","defaultTimeoutInterval":"300000","waitForUI5PollingInterval":400},"useClassicalWaitForUI5":false,"connection":"direct","connectionConfigs":{"direct":{"name":"./connection/directConnectionProvider","binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"83.0.4103.39","unzip":true,"filename":"chromedriver.exe","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_83.0.4103.39","latestVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","executable":{"win32":"chromedriver-83.0.4103.39.exe","mac64":"chromedriver-83.0.4103.39","linux32":"chromedriver-83.0.4103.39","linux64":"chromedriver-83.0.4103.39"}},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"true","untar":"false","filename":"geckodriver.exe","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-win32.zip","latestVersionUrlRedirect":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}},"browserCapabilities":{"browser,chrome":{"android":{"*":{"deviceName":"android"}}},"firefox,ie,edge,safari,chrome,chromium":{"windows,mac,linux":{"*":{"remoteWebDriverOptions":{"maximized":true}}}},"chrome,chromium":{"*":{"*":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]}}}},"safari":{"mac":{"*":{"safaridriverOptions":{"addArguments":["--legacy"]}}}},"chromeMobileEmulation":{"*":{"*":{"browserName":"chrome","remoteWebDriverOptions":{"maximized":false,"scaling":{"x":4,"y":4}},"chromeOptions":{"mobileEmulation":{"deviceMetrics":{"width":360,"height":560,"pixelRatio":4}},"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-infobars"]}}}},"chromeHeadless":{"*":{"*":{"browserName":"chrome","chromeOptions":{"args":["--headless","--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-infobars"]}}}}},"auth":{"sapcloud-form":{"user":"bpadmin","pass":"if*h6UcLwXhB!X","userFieldSelector":"input[name='username']","passFieldSelector":"input[name='password']","logonButtonSelector":"button[class='sapMBtnBase sapMBtn sapMBtnInverted fullButton']","redirectUrl":"https://hcm2preview.sapsf.eu/sf/start?_s.crb=JyveyYRtVEWxZu7Zw2sAR1XL5uc%253d#Shell-home"}},"authConfigs":{"plain":{"name":"./authenticator/plainAuthenticator"},"basic":{"name":"./authenticator/basicUrlAuthenticator"},"fiori-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#USERNAME_BLOCK input","passFieldSelector":"#PASSWORD_BLOCK input","logonButtonSelector":"#LOGIN_LINK"},"sapcloud-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit"},"github-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#login_field","passFieldSelector":"#password","logonButtonSelector":"input[type=submit]","authorizationButtonSelector":"button[type=submit]","authorizationButtonTimeout":10000}},"plugins":[],"matchers":[],"specResolver":"./resolver/localSpecResolver","pageLoading":{"wait":"3000"},"takeScreenshot":{"onExpectFailure":true,"onExpectSuccess":true,"onAction":true},"profile":"integration","baseUrl":"https://hcm2preview.sapsf.eu/login?company=modisT1#/login","specs":{"multiDelete":"./multiDelete.spec.js"},"jasmineNodeOpts":{"showColors":true,"defaultTimeoutInterval":300000},"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"browsers":[{"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}],"conf":"C:\\Workspace\\**project**\\conf.js","reporters":[{"name":"./reporter/screenshotReporter"},{"name":"./reporter/consoleReporter"}],"locators":[{"name":"./locators/jqueryLocator"},{"name":"./locators/controlLocator"}],"osTypeString":"win32","runtimes":[{"browserName":"chrome","platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}]}
DEBUG: Current working directory: C:\Workspace\\**project**
DEBUG: Loading module: ./resolver/localSpecResolver with instance config: {}
INFO: Resolving specs
DEBUG: Resolving specs from: {"multiDelete":"./multiDelete.spec.js"}
Error: No specs found
at C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\uiveri5.js:100:13
    at _fulfilled (C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:854:54)
    at C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:816:13)
    at C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:624:44
    at runSingle (C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:137:13)
    at flush (C:\Users\\**user**\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by maximnaidenov** [comment]
Seems you use spec groups but you do not give the suite name as arg and so nothing is executed. Please have a look at the docs: https://github.com/SAP/ui5-uiveri5/blob/master/docs/usage/specorganization.md
