### ISSUE TITLE
I18NText matcher not supported

### ISSUE THREAD

**Issue by hoangpham97** [SAP/ui5-uiveri5#225]
Hello. Since last week, we have been getting an error saying that I18NText matcher is not supported anymore by UIVERI5. Have anyone encountered this issue?

`
JavascriptError: javascript error: Matcher is not supported! Matcher name: 'I18NText', arguments: '{"propertyName":"text","key":"discard"}'Error: Matcher is not supported! Matcher name: 'I18NText', arguments: '{"propertyName":"text","key":"discard"}'
`
Thank you

**Comment by maximnaidenov** [comment]
UIVeri5 control locators are a very thin wrappers around the OPA declarative matchers. And as seen in the official docs: https://openui5.hana.ondemand.com/api/sap.ui.test.matchers.I18NText, the name of the matcher is i18NText, note the starting lower case. Same applies for all declarative matchers. Till recently, we did not have explicit name validation but with UI5 1.81 we pushed a fix.
