### ISSUE TITLE
W3C false flag not respected

### ISSUE THREAD

**Issue by DanielJakobs** [SAP/ui5-uiveri5#226]
Hi colleagues,

**Jenkins Job:** https://mo-8e981b6d5.mo.sap.corp:2090/jenkins/view/WDF/job/WDF_02_U5_SystemTests/APP=hpa.cei.dm.acc,BROWSER=chrome,TEST_SYSTEM=CC2_352,label=SAP_CEC_QE_Slave4_UIVeri5/28/console

**we start UIVeri5 like this:**
01:33:34 + git pull
01:33:34 Already up-to-date.
01:33:34 + sudo uiveri5 -v ../../../Tools/conf_docker_chrome.js --seleniumAddress=http://127.0.0.1:4444/wd/hub --browsers=chrome --confKeys reporters[0].screenshotsRoot:/home/Jenkins/Automation/Logs/hpa.cei.dm.acc/CC2_352 system:CC2_352 browsers[0].capabilities['goog:chromeOptions'].w3c:false
01:33:34 Warning: Ignoring extra certs from `D:\SAPGlobalRootCA.cer`, load failed: error:02001002:system library:fopen:No such file or directory
01:33:34 Warning: Ignoring extra certs from `D:\SAPGlobalRootCA.cer`, load failed: error:02001002:system library:fopen:No such file or directory
01:33:34 INFO: @ui5/uiveri5 v1.44.0

**The config contains the following:**
  browsers: [{
    browserName: 'chrome',
    capabilities: {
      platform: 'linux', // docker container
      remoteWebDriverOptions: {
        maximized: true
      },
      chromeOptions: {
        args: [
          'disable-infobars',
          'ignore-certificate-errors',
          'test-type',
          'allow-insecure-localhost'
        ],
        w3c: false
      },
      'goog:chromeOptions': {
        w3c: false
      }
    }
  }],

**However, the test fails due to:**
01:36:40 (node:30674) UnhandledPromiseRejectionWarning: UnknownCommandError: unknown command: Cannot call non W3C standard command while in W3C mode
01:36:40     at Object.throwDecodedError (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:514:15)
01:36:40     at parseHttpResponse (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:519:13)
01:36:40     at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30
01:36:40     at processTicksAndRejections (internal/process/task_queues.js:97:5)
01:36:40 From: Task: mouseMove
01:36:40     at WebDriver.schedule (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
01:36:40     at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/actions.js:124:23
01:36:40     at Array.map (<anonymous>)
01:36:40     at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/actions.js:123:29
01:36:40     at TaskQueue.execute_ (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
01:36:40     at TaskQueue.executeNext_ (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
01:36:40     at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27
01:36:40     at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
01:36:40     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Start Up parameters do not reflect w3c:**
01:33:35 DEBUG: Opening remote webdriver session to: http://127.0.0.1:4444/wd/hub
01:33:36 [18:33:36] D/runner - WebDriver session successfully started with capabilities Capabilities {
01:33:36   map_: Map {
01:33:36     'acceptInsecureCerts' => false,
01:33:36     'browserName' => 'chrome',
01:33:36     'browserVersion' => '84.0.4147.89',
01:33:36     'chrome' => {
01:33:36       chromedriverVersion: '84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310})',
01:33:36       userDataDir: '/tmp/.com.google.Chrome.qiOJFT'
01:33:36     },
01:33:36     'goog:chromeOptions' => { debuggerAddress: 'localhost:34588' },
01:33:36     'networkConnectionEnabled' => false,
01:33:36     'pageLoadStrategy' => 'normal',
01:33:36     'platformName' => 'linux',
01:33:36     'proxy' => {},
01:33:36     'setWindowRect' => true,
01:33:36     'strictFileInteractability' => false,
01:33:36     'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
01:33:36     'unhandledPromptBehavior' => 'dismiss and notify',
01:33:36     'webauthn:virtualAuthenticators' => true,
01:33:36     'webdriver.remote.sessionid' => '99116e3a2d15909319c2a458895c4826'
01:33:36   }
01:33:36 }
01:33:36 [18:33:36] D/runner - Running with spec files /home/Jenkins/Automation/GitHub/uiveri5/Applications/hpa.cei.dm.acc/Scenarios/acc.spec.js

Any suggestion to support w3c: false? We need to test drag & drop with mousemove.

Greetings
Daniel

**Comment by maximnaidenov** [comment]
We use old webdriver that does not support the w3c flag at all. By default, chrome still starts in non-w3c mode so no need to set it to off yet. I see you use selenium-server: --seleniumAddress=http://127.0.0.1:4444/wd/hub so maybe the issue is there.

**Comment by Szmydlo** [comment]
We removed browser flag and it works now:

```
hostnamectl;
uptime;
free;
 
sudo docker-compose -f /home/Jenkins/Automation/System/sys-00/docker-compose.yaml restart;
sleep 15; sudo docker ps;
 
cd /home/Jenkins/Automation/GitHub/uiveri5/Applications/$APP/Scenarios;
ls;
git pull;
 
sudo uiveri5 -v ../../../Tools/conf_docker_$BROWSER.js --seleniumAddress=http://127.0.0.1:4444/wd/hub --confKeys reporters[0].screenshotsRoot:'/home/Jenkins/Automation/Logs/'$APP/$TEST_SYSTEM system:$TEST_SYSTEM
```

**Comment by maximnaidenov** [comment]
This browser flag has nothing to do with UIVeri5, as explained we do not handle it in anyway.
