### ISSUE TITLE
File picker

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#230]
Hi Uiveri5 Team,

We have a use case where we need to pick a json file from the system. How is this achievable?

**Comment by hmanchev** [comment]
Hi nipun0212, 

You can try something like: 
```
var path = require('path');

it('should upload json file', function() {
  var filePath = '../some/path/foo.json';
  var absolutePath = path.resolve(__dirname, filePath);

  element(by.*<your input element>)).sendKeys(absolutePath);    
  element(by.id('<upload button>')).click();
});
 ```

Keep in mind this will not work in any cases or browsers.

Best Regards,
Hristo

**Comment by nipun0212** [comment]
Hi Hristo,

Do you have any code sample which works on Jenkins?

With Regards,
Nipun

**Comment by hmanchev** [comment]
Hi Nipun,

Why you think there will be difference if it is executed on Jenkins?

BR,
Hristo

**Comment by nipun0212** [comment]
Hi Hristo,

What to give in directory attribute on jenkins?

With Regards,
Nipun Madan

**Comment by maximnaidenov** [comment]
@nipun0212 How do we know what is your jenkins installation ?. Hristo gave you a code sample, please adapt to your needs.

**Comment by nipun0212** [comment]
Thanks Hristo and Maxim. The snippet is working fine.
