### ISSUE TITLE
Expectation FAILED: Failed: Waiting for redirection to complete, target url:

### ISSUE THREAD

**Issue by arv-inc** [SAP/ui5-uiveri5#231]
Hello to everyone!
My test fail with this log:

> PS D:\GitRepos\SafeERP_smoke> uiveri5
> DevTools listening on ws://127.0.0.1:65428/devtools/browser/895e02d2-85b0-46d0-8acb-b4e1a2e2ebe6
> INFO: Suite started: teched
> INFO: Spec started: Should validate the home screen
> INFO: Opening: https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs
> **INFO: Expectation FAILED: Failed: Waiting for redirection to complete, target url:** https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs
> Wait timed out after 9901ms
> INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
>     at findByControl (eval at executeScript (:480:16), <anonymous>:5:13)
>     at eval (eval at executeScript (:480:16), <anonymous>:30:6)
>     at executeScript (<anonymous>:482:30)
>     at <anonymous>:487:24
>     at callFunction (<anonymous>:450:22)
>     at <anonymous>:464:23
>     at <anonymous>:465:3
>   (Session info: chrome=85.0.4183.83)
>   (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Windows NT 10.0.18363 x86_64)
> INFO: Spec finished: Should validate the home screen with status: FAILED
> INFO: Suite finished: teched with status: FAILED for: 13.478s
> INFO: Suite specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0
> INFO: Suite expectations summary, total: 2, passed: 0, failed total: 2, failed with error: 2, failed with image comparison: 0
> INFO: Overall status: FAILED for: 13.562s
> INFO: Overall suites summary, total: 1, passed: 0, failed: 1
> INFO: Overall specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0
> INFO: Overall expectations summary, total: 2, passed: 0, failed total: 2, failed with error: 2, failed with image comparison: 0
> [16:48:53] I/launcher - 0 instance(s) of WebDriver still running
> [16:48:53] I/launcher - chrome #01 failed 1 test(s)
> [16:48:53] I/launcher - overall: 1 failed spec(s)
> [16:48:53] E/launcher - Process exited with error code 1
> 

My **conf.js**:

```
exports.config = {
     profile: "integration",
     baseUrl: "https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs",
     browsers: [{
         browserName: 'chrome',
         capabilities: {
           chromedriverOptions: {
             loggingTo: 'chromedriver.log',
           },
           chromeOptions: {
             args: [
                  'start-maximized',
                 'ignore-certificate-errors',
                 'disable-popup-blocking'
                 // 'remote-debugging-port=9099'
             ]
           }
         }
       }],
};
```

**But in the screenshot I see that the page is open**:
![image](https://user-images.githubusercontent.com/41366776/91991638-cf00a200-ed3b-11ea-99cb-803698145e45.png)

Please help!!!

**Comment by maximnaidenov** [comment]
Hi,
please note that you need to put the FINAL url that you see when opening the page manually in baseUrl. You put there: https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs but obviously this is not the final URL and thats why the redirect never completed.
Also note it is extremely bad idea to put user and pass in the URL !!!

**Comment by arv-inc** [comment]
> Hi,
> please note that you need to put the FINAL url that you see when opening the page manually in baseUrl. You put there: https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs but obviously this is not the final URL and thats why the redirect never completed.
> Also note it is extremely bad idea to put user and pass in the URL !!!

It's strange, this is the final url, all work is done here.
...
I try to set password inside conf.js like this:
```
exports.config = {
    profile: "integration",
    baseUrl: "https://ip_local:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs",
    auth: {'sapcloud-form': {
          user: 'admin',
          pass: 'password123' }},
```
But authorization fails.
Only work if i set in command line
uiveri5 --params.user=<user> --params.pass=<pass>

**Comment by arv-inc** [comment]
I think i find the problem...
If i made authorisation manualy in chrome pop-up window after test start:
![image](https://user-images.githubusercontent.com/41366776/92122316-f458e300-ee03-11ea-8532-32af64629e5c.png)

Test work fine
```
DevTools listening on ws://127.0.0.1:56261/devtools/browser/7d52786b-5f64-4e26-9f91-5a31cc9be748
INFO: Suite started: teched
INFO: Spec started: Should validate the home screen
INFO: Opening: https://local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs
INFO: UI5 Version: 1.60.13
INFO: UI5 Timestamp: 
INFO: Spec finished: Should validate the home screen with status: PASSED
INFO: Suite finished: teched with status: PASSED for: 16.301s
INFO: Suite specs summary, total: 1, passed: 1, failed: 0, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 1, passed: 1, failed total: 0, failed with error: 0, failed with image comparison: 0
INFO: Overall status: PASSED for: 16.314s
INFO: Overall suites summary, total: 1, passed: 1, failed: 0
INFO: Overall specs summary, total: 1, passed: 1, failed: 0, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 1, passed: 1, failed total: 0, failed with error: 0, failed with image comparison: 0
[16:30:36] I/launcher - 0 instance(s) of WebDriver still running
[16:30:36] I/launcher - chrome #01 passed
```

Mybe Uiveri5 wait redirect to https://login:password123@local_ip:8001/sap/bc/ui5_ui5/GAZIS/serp/index.html#/cs , and fail...

Why auth in my conf didn`t work? Made like in manual

**Comment by arv-inc** [comment]
I set auth form 'basic in conf.js', now all work fine.
auth: {
      // form based
      'basic': {
          user: 'login',
          pass: 'password'
      }
    },
