### ISSUE TITLE
Veri5 doesn't detect dependencies after login and receive timeout

### ISSUE THREAD

**Issue by saard** [SAP/ui5-uiveri5#232]
16:22:32  INFO: Expectation FAILED: Failed: Waiting for redirection to complete, target url: http://****.cfapps.sap.hana.ondemand.com/sitedirectory
16:22:32  Wait timed out after 59905ms
16:22:32  INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
16:22:32      at findByControl (eval at executeScript (:480:16), <anonymous>:5:13)
16:22:32      at eval (eval at executeScript (:480:16), <anonymous>:30:6)
16:22:32      at executeScript (<anonymous>:482:30)
16:22:32      at <anonymous>:487:24
16:22:32      at callFunction (<anonymous>:450:22)
16:22:32      at <anonymous>:464:23
16:22:32      at <anonymous>:465:3
16:22:32    (Session info: headless chrome=84.0.4147.89)
16:22:32    (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 4.19.112+ x86_64)
16:22:32  INFO: Spec finished: Create new Site with status: FAILED
16:22:32  INFO: Spec started: Switch to Content Manager 
16:22:32  *** Responses start ***

**Comment by maximnaidenov** [comment]
http://****.cfapps.sap.hana.ondemand.com/sitedirectory is not a UI5 application

**Comment by saard** [comment]
Hi Maxim,

I removed the full URL for privacy.
if you want it I can send it to you directly.

BR,
Saar

**Comment by saard** [comment]
![image](https://user-images.githubusercontent.com/3519995/92102646-8999ae80-ede7-11ea-9764-14787baf8672.png)

this is from our report

**Comment by arv-inc** [comment]
Looks like same problem
https://github.com/SAP/ui5-uiveri5/issues/231

**Comment by maximnaidenov** [comment]
The error message says this is not a UI5 app and looking at the screenshot, I would say the same. Can you open the UI5 Inspector on this page and show me the control tree ?

**Comment by saard** [comment]
Hi Maxim,

no problem, just an FYI this works on several landscapes (different URL's same exact app)
and on some it doesn't

![image](https://user-images.githubusercontent.com/3519995/92121605-23228980-ee03-11ea-8fbb-16451e177f05.png)

**Comment by maximnaidenov** [comment]
The "waiting for redirect" is a different issue and means that the URL you specified in baseURl is not the same as the final URL you see in the browser when the app is loaded.

**Comment by saard** [comment]
Thank you Maxim,
The URL after login indeed added a /sites and according to your comment I understood that this is the reason why login wasn't identified.
