### ISSUE TITLE
High Severity vulnerability in ETD-Cloud product Whitesource scan due to old dependencies in @ui5/uiveri5

### ISSUE THREAD

**Issue by ababalau** [SAP/ui5-uiveri5#238]
Hi, 
When currently running Whitesource on our SAP ETD CLOUD RELEASE product, we get 2 HIGH vulnerabilities:
![image](https://user-images.githubusercontent.com/24736185/92712744-c5da8b00-f362-11ea-872b-887b09a667af.png)

After analysis we realized they both come from some older dependencies present in the latest version (1.44.0) @ui5/uiveri5 dependencies tree, that we use for testing our UIs:

"dependencies": {
    "adm-zip": "^0.4.7",
    "glob": "~4.3.5",  --> "mimimatch": "2.0.10"
    "lodash": "^4.17.2",
...............................
}

In order the 2 High vulnerabilities to be fixed, 
it would be needed that uiver5 be re-built with the indicated versions or higher (preferably latest available):

"dependencies": {
    "adm-zip": "^0.4.9", (adding this for we have another medium vulnerability requiring this version)
    "glob": "~7.1.6",  --> "mimimatch": "^3.0.4"
    "lodash": "^4.17.20",
...............................
}

The pb is, that we need to have these issues fixes in WS, because with the current Product compliance rules, our release will not be approved.

Thank you,
Adrian Babalau

**Comment by maximnaidenov** [comment]
Hi Adrian,
please note UIVeri5 is a console based, test tool. It is NOT SHIPPED with the product so there is NO WAY your delivery to dependent on anything in the test tool. The mentioned vulnerabilities are relevant to server code and in no way could affect CONSOLE-BASED application like uiveri5.
So please mark those as "not relevant" in your whitelisting system.

**Comment by ababalau** [comment]
Ok. Sorry for the delay in answering. 
I fixed these issues on our side by moving ui5veri5 and some other testing related dependencies in devDependencies (my colleagues have placed it initially in the dependencies section of each of our UIs package.json, but that is of course not needed as you also imply). Ticket closed.
