### ISSUE TITLE
Option to disable password logging (console and\or Sauce lab report)

### ISSUE THREAD

**Issue by adrianna-u** [SAP/ui5-uiveri5#239]
Hi,
we are using UIVeri5 for testing our UI5 apps. We are running the tests on Sauce labs.

We would like to use the sauce lab logger. However this logger is logging the password on Sauce labs.
![image](https://user-images.githubusercontent.com/71085376/92749139-1e6f4f80-f386-11ea-91fb-b4b6d1fd811c.png)

What would you recommend? We have written own SauceLabs report (also using sauce labs context) but would like to replace it by the standard one.

So could you offer option, to disable password logging?

 - Remove "SEND KEYS":  Disabling the Sauce lab logger on jasmineStarted: browser.executeScript("sauce: disable log"); Reenable on suiteStarted
 - Remove "Perform action:send keys" Disable it also in the Sauce labs report

Thanks
Adrianna

**Comment by maximnaidenov** [comment]
Hi, 
the "perform action ..." log comes from the saucelabsReporter in UIVeri5 that you have explicitly enabled: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/reporters.md. Of course, you can disable it and you want see those logs.
the SEND KEYS logs are standard SauceLabs command logs, I have no idea how to disable them (if possible at all), please contact SauceLabs support for this.
Anyway, I would question if you really need this level of anonymization. This is a testing tool and testing system and not a productive system where you keep customer data. You should use dedicated service users so the eventual exposure of its password is not an issue. And finally, you should always control the access to those logs as they inevitably contain credentials. IMHO the hard requirement to avoid logging passwords applies to the server component and in the context of user data. And does not mean all test tools should be twisted also.

**Comment by adrianna-u** [comment]
Hi Maxim,

The results of tests are shared with broad audience, but the dedicated technical user details should not be shared. 
Sauce Labs offers the option "disable log" exactly for this use case of sensitive data usage.

Yes, we have explicitly enabled your reporter https://github.com/SAP/ui5-uiveri5/blob/master/src/reporter/saucelabsReporter.js , because its is really usefull, when logging what specs are started, what tests passed etc. 
So I belive using UIVeri5 with SauceLabs really need this report, therefore we don't want to disable it, but would like to ask for an enhancement. We have implemented custom logger doing the same, but we would like to use standard one, as we will have many applications using the setup and your logger is perfect for this case.

Th SEND KEYS logs are standard SauceLabs logger, and can be disabled by browser.executeScript("sauce: disable log"). We are doing it in our custom reporter and it is working.  https://github.wdf.sap.corp/catering/lunchmenu-e2e-tests/blob/master/reporters/sauceLab-report.js
By doing the same , just for the Log-In phase, you would avoid "SEND KEYS ... " and "perform action ... ".

I can imagine, when more and more projects start using your new SauceLabs reporter, this feature request could be valid for them as well.

Thanks
Adrianna

**Comment by maximnaidenov** [comment]
Hi Adrianna, 
this request sounds reasonable, we have some specific handling for console logs in the authenticators so definitely we could do something similar for saucelabsReporter. I will add this to our BL and we will address it soon. As for the disabling of saucelabs execution log, I am somehow hesitant to control it from uiveri5. Maybe we could include a sample in our docs how to disable them also.

**Comment by maximnaidenov** [comment]
Hi Adrianna, 
I just released a version that contains this functionality: https://github.com/SAP/ui5-uiveri5/releases/tag/v1.45.1. Please have a look if it suits your needs. 
We have some more improvements for the saucelabs integration in our pipeline. We plan to have a link in our console logs that directly points to the respective execution in saucelabs dashboard. And the opposite - to log a link to the pipeline logs in the saucelabs logs. But this will take some time to complete.

**Comment by adrianna-u** [comment]
Hi Maxim,

thanks for providing the fix so quick. We have integrated the reporter. It looks good.

Looking forward to upcomming changes.

Thanks,
Adrianna
