### ISSUE TITLE
Binding-Context / Object Access

### ISSUE THREAD

**Issue by timostark** [SAP/ui5-uiveri5#25]
Hi,

I already asked a similar question in #12 - I am not 100% sure though if i got you correctly here.
Example: I want to select Order Id 7991 in your demo-application browse-orders ( https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/orderbrowser/webapp/test/mockServer.html ).

![image](https://user-images.githubusercontent.com/19237828/53545721-abe3a980-3b2a-11e9-8cfa-4e97d089d8de.png)

The order ID however is not available as "clean-technical-identifier". I can only ask for the Property title ("Order 7991"), which might be language dependent. If I check the binding context of this object, i see that the information I want, is perfectly available.
![image](https://user-images.githubusercontent.com/19237828/53545868-24e30100-3b2b-11e9-9296-f940dcab67eb.png)

So I would expect a matcher:
`BindingContext: { model: undefined, path: 'OrderID', value: 7991}`

Unfortunatly the documentation of openui5 does not seem to provide such a matcher.
So the question: Where am I missing something here in that use case? Or are you "accepting" tests to be based on language dependent texts?

Regards,
Timo

**Comment by vobu** [comment]
hi,
sounds as if
```
element(by.control({
  viewName: "myViewName",
  controlType: "sap.m.StandardListItem",
  bindingPath: {
    path: "/products/7991", 
    propertyPath: "OrderID", 
    modelName: ""
  }
});
```
is what you‘re looking for (freehand coding of the above, so read with caution :)
hth, v.

**Comment by maximnaidenov** [comment]
We recently added an example in OPA docs: https://openui5nightly.hana.ondemand.com/#/topic/21aeff6928f84d179a47470123afee59.html
Everything applied equally to uiveri5 of course.

**Comment by timostark** [comment]
Hi Volker, Maxim,

OK - I've chosen a bad example again :-) Yes - in this case the absolute binding path would be perfect, as I am searching for the primary key. You are right. Thanks for this.

Still it is not 100% the flexibility I'd hoped for. As a more general requirement, I'd like to have full access to the model-object behind the binding path. So another example (for the same URL) - I have a complex search, and if I am searching for a specific "value" i am only expecting results with "ShipVia": 6419 - even though there is no single visible control on the screen, which is showing the Ship-Via.

![image](https://user-images.githubusercontent.com/19237828/53547494-7bead500-3b2f-11e9-9ec8-1978606c1da4.png)

In such a case I really do not see a way to use that binding path, right?

Thanks again,
Timo

**Comment by maximnaidenov** [comment]
Hi Timo,
uiveri5 and OPA are intended to simulate user interactions. And because the user can't interact with invisible controls, you are not supposed to locate such. In OPA, due to historical reasons, you can avoid this limitation by adding visible: false in the selector but we do not support this in uiveri5 very intentionally. As for exposing "model object", this is not practical in uiveri5 as the locators are executed in UI5 runtime, not in test(nodejs) environment. 
By the way, the BindingPath matcher is very powerful, we are not aware of a single practical use case that is not supported. If you ever met such, please share it so we could possibly plan and extend the binding path matcher.

**Comment by timostark** [comment]
Ok - perfect. That is an answer i can totally agree with.

One more question: You are using the MatcherFactory internally ( https://github.com/SAP/openui5/blob/2fc8e8ebc9ee447c5976062f59e243d193484b0d/src/sap.ui.core/src/sap/ui/test/matchers/ ). 

Unfortunately this one is *hardcoding* the supported matchers.
![image](https://user-images.githubusercontent.com/19237828/53548237-4f37bd00-3b31-11e9-9312-c04d4af3dbaa.png)

Theoretically it is possible to create custom matchers (inherting from sap.ui.test.matchers.Matcher ) - which are out of scope due to that hardcoding. 
Do you have any plans of opening this stuff up?

Thanks,
Timo

**Comment by maximnaidenov** [comment]
Hi Timo,
if there is interest and realistic use case, we could work on support for custom matchers.

**Comment by timostark** [comment]
Ok Great :-) I adjusted my test-recorder to comply with the guideline to focus on binding paths (and visible properties). Working pretty well without the need for a custom matcher at the moment.

Thanks again for your help --> closing this issue.
![image](https://user-images.githubusercontent.com/19237828/53555523-64691780-3b42-11e9-85a6-f8c6422f9661.png)
