### ISSUE TITLE
issues in UI after clicking

### ISSUE THREAD

**Issue by abhee99** [SAP/ui5-uiveri5#255]
![issue](https://user-images.githubusercontent.com/25304032/98210978-67e3b180-1f67-11eb-8584-0fc24a724a57.png)
In the image a gear button is visible in which loading is happening.

If manually I am clicking gear Button loading does not happen but when same thing is done by scripts this loading appears and even after I press OK in dialog in script that loading still is there due to which I cannot perform furthur task.

**Comment by abhee99** [comment]
![Screenshot (134)](https://user-images.githubusercontent.com/25304032/98211928-d412e500-1f68-11eb-8996-d5ae746be771.png)
This is simple code which is bieng executed let say:
Here:
1)Clicking Gear Button and wait for 10s
2)Click on OK in dialog and wait for 10s

Even after pressing OK and wait for 10s that loading still happen in active UI

**Comment by maximnaidenov** [comment]
I do not see any gear button on this screenshot ?

**Comment by abhee99** [comment]
![Inkedissue_LI](https://user-images.githubusercontent.com/25304032/98215176-79c85300-1f6d-11eb-8b31-42ed2610b813.jpg)
This is the gear button which is bieng clicked and this loading appears
This loading does not appear when i click it manually in UI only happens when script clicks

**Comment by maximnaidenov** [comment]
This most likely means that you do not follow the same scenario and/or use different user/rights. The testing tool doesn't do anything miraculous, it does not "know" your application so to "trick it" somehow. It simply simulates a user click on the element you have given.

**Comment by abhee99** [comment]
![Screenshot (136)_LI](https://user-images.githubusercontent.com/25304032/98217551-a92c8f00-1f70-11eb-9763-19e0c5d52123.jpg)

but since my goal it to add some data in the dialog box and then press OK, so after that a link appears where I have highlighted in the picture but this loading should'nt be there and due to loading the link is not appearing but actually it is suppose to appear.

**Comment by abhee99** [comment]
![Screenshot (137)](https://user-images.githubusercontent.com/25304032/98217770-f3ae0b80-1f70-11eb-9d66-346e7c00c33e.png)
This screenshot I have taken when I manually click gear button in the application then there is no loading appearing

**Comment by maximnaidenov** [comment]
I am sorry but I do not see how your issues have anything to do with the testing framework and so I can;'t help.
