### ISSUE TITLE
Continue on failure

### ISSUE THREAD

**Issue by arv-inc** [SAP/ui5-uiveri5#258]
Hello!
I have test:
```
    it("Сreate Project CS", function() {
        When.onTheCSPage.iClickOnCreateButton();
        Then.onTheCSPage.iShouldSeeProjectFields();
        When.onTheCSPage.iInputCSProjectName(projectName);
        When.onTheCSPage.iSelectGroupAndAgent();
        Then.onTheCSPage.iShouldSeeObject();
        When.onTheCSPage.iSelectProfile();
        Then.onTheCSPage.iShouldSeeMyProject(projectName);
    })
```
Test fail expect on _Then.onTheCSPage.iShouldSeeObject();_

`INFO: Expectation FAILED: Expected 'No prod' to be 'Prod'.`

I know about this problem

But i want contiunue test execution to the end.

How should I do it?

**Comment by maximnaidenov** [comment]
Actually test execution continues respectively or assertions status. Why do you think your test stops ?

**Comment by arv-inc** [comment]
You are right the test continued. I misidentified the problem.

Thank you!
