### ISSUE TITLE
Regular Expressions for text properties do not work in Firefox 

### ISSUE THREAD

**Issue by ruzickam** [SAP/ui5-uiveri5#280]
Dear UIveri5 team,

I have discovered that Regular Expressions for text properties do not work in Firefox. An example of a control locator with RegExp is shown below:

`element( by.control ( {  controlType: "sap.m.Title", properties: { text: new RegExp("Hello") } } ) )`

This element is found in Chrome, but not in Firefox. When I omit the RegExp and use just
`{ text: "Hello" }`
everything works fine even in Firefox.

An interesting fact is that when the RegExp is used for an 'id', the locator is found in both Chrome and Firefox.

Is there any limitation in Firefox that would prevent of using the RegExp for text property?

Thank you,
Michal

**Comment by tsaleksandrova** [comment]
fixed in 1.46.2
