### ISSUE TITLE
SauceLabs-Tests: Driver info: driver.version: unknown

### ISSUE THREAD

**Issue by ThommySte** [SAP/ui5-uiveri5#283]
Hi colleagues,
Since today after a lot of otehr hickup all of my SauceLabs test are broken - the "local" uiVer5Test are running.

Firefox:
E/launcher - Unable to create new service: GeckoDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'dynamic-agent-8aa5bb7e-60a5-4224-b185-f86fe10d9e09-td889-v196l', ip: '192.168.200.220', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.112+', java.version: '1.8.0_275'
Driver info: driver.version: unknown
E/launcher - SessionNotCreatedError: Unable to create new service: GeckoDriverService

or Chrome:
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"Windows 10","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--incognito"]},"tunnelIdentifier":"sap-intranet","parentTunnel":"S-A-P","extendedDebugging":true,"count":1,"loggingPrefs":{"browser":"SEVERE"}}

[16:35:23] E/launcher - session not created: No matching capabilities found

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'

System info: host: 'dynamic-agent-bde890ae-984b-4286-b28c-bc76f4d0ee78-pvcx6-wn38r', ip: '192.168.203.65', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.112+', java.version: '1.8.0_275'
Driver info: driver.version: unknown
remote stacktrace: #0 0x55be8e3b9199 <unknown>
[16:35:23] E/launcher - SessionNotCreatedError: session not created: No matching capabilities found
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'dynamic-agent-bde890ae-984b-4286-b28c-bc76f4d0ee78-pvcx6-wn38r', ip: '192.168.203.65', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.112+', java.version: '1.8.0_275'
Driver info: driver.version: unknown
remote stacktrace: #0 0x55be8e3b9199 <unknown>
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()

Same for Edge.

Regarding your docu - https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md I will use everytime the latest.
I don't understand why this occurs now -  There was no change in.

Runtime environment - Using a stable Piper/Piper-Os library to reduce  problems.

Thanks, Thomas

**Comment by maximnaidenov** [comment]
Hi Thomas,

can you please provide the first few lines of UIVeri5 logs where I could see the cmd args? Please anonymise the token but please leave everything else intakt. These logs seems to show local execution and you mention SauseLabs. I know that piper dev did some breaking changes recently that affected remote execution, can you please validate ?

**Comment by ThommySte** [comment]
Hi Maxim, yes Piper break the everything - that's why I using now a Piper/Piper-OS the older non master version before the breaking changes -  I send you all as links on Slack.

**Comment by ThommySte** [comment]
Issue solved, the problem was caused by the changed defaults.
Thanks, for the support.
