### ISSUE TITLE
Problems with matching percentage when using visual comparison with a version > 1.44.1

### ISSUE THREAD

**Issue by ramondebeijer** [SAP/ui5-uiveri5#293]
Hi when we use visual comparison in our uiveri5 
expect(takeScreenshot()).toLookAs(Page);

then up to version 1.44.1 I get the following in the report:
Expectation FAILED: Image comparison failed, reference image: NotFound, difference in percentages: 0.03% (threshold: 0.1%), difference in pixels: 671 (threshold: 0.5) ,update disabled

in the versions after that it does something wrong with base64 encoding I think? Because then we get:
Expectation FAILED: Expected 'iVBORw......a very long string here.....ssdad0==' toLookAs 'NotFound'

Is something broken? do I need to configure something different?

regards Ramon

**Comment by maximnaidenov** [comment]
Hi,
we run a lot of Visual tests for openui5 and I just checked that we use UIVeri5 1.46.1 and we do not see any such issues. Specially the based64 encoding is coming from the browser e.g. the screenshot that we get with browser.driver.takeScreenshot()  is returned as base64 encoded string and we decode it with: var screenshotBuffer = new Buffer(fullScreenshot, 'base64'); 
I suspect that the "NotFound" maybe the reason e.g. if the stored screenshot is removed somehow ?. How do yo store the images ?
Please provide a debug log (-v on console) so I could have a look and try to help you.

**Comment by ramondebeijer** [comment]
hi @maximnaidenov I will try to upload some debug logging here later, but as it does work with 1.44.1 is there something changed in the way we should configure/setup the tests? Is there some sample project somewhere that demonstrates how to setup the visual testing with UIveri5 so I can check it against our setup?

**Comment by maximnaidenov** [comment]
Hi,
officially we do not support visual testing in uiveri5 and so there is no explicit guide, documentation and sample project. With the reason that our practice showed that visual testing is not suitable for application testing due to the many factors that influence the screenshots - OS, browser, ui5 visual changes and so on. So we keep it working only for limited set of internal openui5 visual test cases where we control the environment very tightly.
But as you have configured it and use it, I will glad to help you. Please share a debug log and I will compare against out setup.
We have not done any intentional changes in 1.44 and our setup works  the same way for the last 3 years.

**Comment by ramondebeijer** [comment]
hi @maximnaidenov  is there a way i can send you the logs and possible (if needed) some config files in a private message somewhere?

**Comment by ramondebeijer** [comment]
Hopefully this is what you meant?

`INFO: @ui5/uiveri5 v1.46.2
DEBUG: Config from command-line: {"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"conf":"/workingdirectory/app/webapp/test/e2e/conf.js"}
DEBUG: Loading default config from: /workingdirectory/app/webapp/test/e2e/conf.js
DEBUG: Loading config from: /workingdirectory/app/node_modules/@ui5/uiveri5/conf/integration.profile.conf.js
DEBUG: Adding module with ID "undefined" and name "./reporter/screenshotReporter"under key "reporters"
DEBUG: Loading common profile config from: ../conf/profile.conf.js
DEBUG: Adding module with ID "undefined" and name "./reporter/consoleReporter" under key "reporters"
DEBUG: Adding module with ID "undefined" and name "./locators/jqueryLocator"under key "locators"
DEBUG: Adding module with ID "undefined" and name "./locators/controlLocator"under key "locators"
DEBUG: Adding module with ID "undefined" and name "./plugins/browserLogsPlugin"under key "plugins"
DEBUG: Loading module: ./plugins/browserLogsPlugin with instance config: {}
DEBUG: Resolved runtime: {"browserName":"chrome","platformResolution":"1600x1200","capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"browserName":"chrome"},"platformName":"mac","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}
DEBUG: Config after resolving config file and profile: {"timeouts":{"waitForUI5Delta":200,"getPageTimeout":10000,"allScriptsTimeout":11000,"defaultTimeoutInterval":"300000","waitForUI5PollingInterval":400},"useClassicalWaitForUI5":false,"connection":"direct","connectionConfigs":{"direct":{"name":"./connection/directConnectionProvider","binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_mac64.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestMajorVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","latestVersionDirectUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE","useDirectUrl":true,"executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"}},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"false","untar":"true","filename":"geckodriver","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-macos.tar.gz","latestVersionRedirectUrl":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}},"browserCapabilities":{"browser,chrome":{"android":{"*":{"deviceName":"android"}}},"firefox,ie,edge,safari,chrome,chromium":{"windows,mac,linux":{"*":{"remoteWebDriverOptions":{"maximized":true}}}},"chrome,chromium":{"*":{"*":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]}}}},"safari":{"mac":{"*":{"safaridriverOptions":{"addArguments":["--legacy"]}}}},"chromeMobileEmulation":{"*":{"*":{"browserName":"chrome","remoteWebDriverOptions":{"maximized":false,"scaling":{"x":4,"y":4}},"chromeOptions":{"mobileEmulation":{"deviceMetrics":{"width":360,"height":560,"pixelRatio":4}},"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-infobars"]}}}},"chromeHeadless":{"*":{"*":{"browserName":"chrome","chromeOptions":{"args":["--headless","--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-infobars"]}}}}},"auth":"plain","authConfigs":{"plain":{"name":"./authenticator/plainAuthenticator"},"basic":{"name":"./authenticator/basicUrlAuthenticator"},"fiori-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#USERNAME_BLOCK input","passFieldSelector":"#PASSWORD_BLOCK input","logonButtonSelector":"#LOGIN_LINK"},"sapcloud-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit"},"github-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#login_field","passFieldSelector":"#password","logonButtonSelector":"input[type=submit]","authorizationButtonSelector":"button[type=submit]","authorizationButtonTimeout":10000}},"matchers":[],"log":{"browser":{"level":"SEVERE"}},"specResolver":"./resolver/localSpecResolver","pageLoading":{"wait":"3000"},"takeScreenshot":{"onExpectFailure":true,"onExpectSuccess":true,"onAction":true},"profile":"integration","specs":"specs/NotFound*","take":true,"compare":true,"update":false,"thresholdPixels":50,"storageProvider":{"name":"./image/localStorageProvider","refImagesRoot":"./reference","actImagesRoot":"./target"},"screenshotProvider":{"name":"./image/localScreenshotProvider","screenshotSleep":100},"comparisonProvider":{"name":"./image/localComparisonProvider"},"browsers":[{"browserName":"chrome","platformResolution":"1600x1200","capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"browserName":"chrome"},"platformName":"mac","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}],"baseUrl":"http://localhost:5050/app/index_Mock.html#/myCases","useSeleniumJar":false,"seleniumLoopback":false,"ignoreNothing":true,"v":1,"verbose":1,"conf":"/workingdirectory/app/webapp/test/e2e/conf.js","reporters":[{"name":"./reporter/screenshotReporter"},{"name":"./reporter/consoleReporter"}],"locators":[{"name":"./locators/jqueryLocator"},{"name":"./locators/controlLocator"}],"plugins":[{"name":"./plugins/browserLogsPlugin"}],"osTypeString":"mac64","runtimes":[{"browserName":"chrome","platformResolution":"1600x1200","capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"browserName":"chrome"},"platformName":"mac","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}]}
DEBUG: Current working directory: /workingdirectory/app/webapp/test/e2e
DEBUG: Loading module: ./resolver/localSpecResolver with instance config: {}
INFO: Resolving specs
DEBUG: Resolving specs from: ["specs/NotFound*"]
DEBUG: Spec found, name: NotFound , path: /workingdirectory/app/webapp/test/e2e/specs/NotFound.spec.js , url:http://localhost:5050/app/index_Mock.html#/myCases
DEBUG: Loading module: ./connection/directConnectionProvider with instance config: {"binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_mac64.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestMajorVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","latestVersionDirectUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE","useDirectUrl":true,"executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"}},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"false","untar":"true","filename":"geckodriver","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-macos.tar.gz","latestVersionRedirectUrl":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}
DEBUG: Setting getPageTimeout: 10000
DEBUG: Setting allScriptsTimeout: 11000
DEBUG: Setting defaultTimeoutInterval: 300000
DEBUG: Resolved protractor multiCapabilities: [{"browserName":"chrome","platform":"MAC","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"runtime":{"browserName":"chrome","platformResolution":"1600x1200","capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"browserName":"chrome"},"platformName":"mac","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}}]
DEBUG: Loading BDD-style page object factory
DEBUG: Setting up connection provider environment
INFO: Check for latest version of: chromedriver from: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
(node:13783) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found latest version of chromedriver: 89.0.4389.23
INFO: Found correct binary locally: /workingdirectory/app/node_modules/@ui5/uiveri5/selenium/chromedriver-89.0.4389.23
INFO: Executing 1 specs
[13:06:24] D/launcher - Running with --troubleshoot
[13:06:24] D/launcher - Protractor version: 5.3.2
[13:06:24] D/launcher - Your base url for tests is http://localhost:5050/app/index_Mock.html#/myCases
[13:06:24] D/plugins - Plugin "Plugin #0" loaded.
[13:06:24] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"MAC","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"count":1,"loggingPrefs":{"browser":"SEVERE"}}
DEBUG: Starting local chromedriver with executable: /workingdirectory/app/node_modules/@ui5/uiveri5/selenium/chromedriver-89.0.4389.23
[13:06:25] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_:
   Map {
     'acceptInsecureCerts' => false,
     'acceptSslCerts' => false,
     'applicationCacheEnabled' => false,
     'browserConnectionEnabled' => false,
     'browserName' => 'chrome',
     'chrome' => { chromedriverVersion:
        '89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294})',
       userDataDir:
        '/var/folders/39/lkdc6h2x5d79d_7m158ynynr0000gn/T/.com.google.Chrome.ayt2HT' },
     'cssSelectorsEnabled' => true,
     'databaseEnabled' => false,
     'goog:chromeOptions' => { debuggerAddress: 'localhost:55896' },
     'handlesAlerts' => true,
     'hasTouchScreen' => false,
     'javascriptEnabled' => true,
     'locationContextEnabled' => true,
     'mobileEmulationEnabled' => false,
     'nativeEvents' => true,
     'networkConnectionEnabled' => false,
     'pageLoadStrategy' => 'normal',
     'platform' => 'Mac OS X',
     'proxy' => {},
     'rotatable' => false,
     'setWindowRect' => true,
     'strictFileInteractability' => false,
     'takesHeapSnapshot' => true,
     'takesScreenshot' => true,
     'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
     'unexpectedAlertBehaviour' => 'ignore',
     'version' => '89.0.4389.72',
     'webStorageEnabled' => true,
     'webauthn:extension:largeBlob' => true,
     'webauthn:virtualAuthenticators' => true } }
[13:06:25] D/runner - Running with spec files /workingdirectory/app/webapp/test/e2e/specs/NotFound.spec.js
DEBUG: Loading module: ./reporter/screenshotReporter with instance config: {}
DEBUG: Loading module: ./reporter/consoleReporter with instance config: {}
DEBUG: Loading module: ./locators/jqueryLocator with instance config: {}
DEBUG: Loading module: ./locators/controlLocator with instance config: {}
DEBUG: Registering jquery locator
DEBUG: Registering control locator
INFO: Suite started: NotFound
DEBUG: Runtime resolved from capabilities: {"browserName":"chrome","platformResolution":"1600x1200","capabilities":{"chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","--headless","window-size=1600x1200"]},"remoteWebDriverOptions":{"maximized":true},"browserName":"chrome"},"platformName":"mac","browserVersion":"*","platformVersion":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}
DEBUG: Loading module: ./image/localScreenshotProvider with instance config: {"screenshotSleep":100}
DEBUG: Loading module: ./image/localStorageProvider with instance config: {"refImagesRoot":"./reference","actImagesRoot":"./target"}
DEBUG: Loading module: ./image/localComparisonProvider with instance config: {}
DEBUG: Maximizing browser window
INFO: Spec started: should open Not Found view
DEBUG: Loading module: ./authenticator/plainAuthenticator with instance config: {}
INFO: Opening: http://localhost:5050/app/index_Mock.html#/myCases
DEBUG: Waiting for redirect to complete, current url: http://localhost:5050/app/index_Mock.html#/myCases
DEBUG: Initial page load wait: 3000ms
INFO: UI5 Version: 1.71.25
INFO: UI5 Timestamp: 202009081410
DEBUG: Init localStorageProvider with spec: NotFound
INFO: Opening: http://localhost:5050/app/index_Mock.html#/myCasesabcde
DEBUG: Waiting for redirect to complete, current url: http://localhost:5050/app/index_Mock.html#/myCasesabcde
DEBUG: Initial page load wait: 3000ms
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-open-Not-Found-view_0_pass_2021-03-05T12-06-31.png"
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-open-Not-Found-view_1_pass_2021-03-05T12-06-32.png"
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-open-Not-Found-view_2_pass_2021-03-05T12-06-33.png"
DEBUG: Taking actual screenshot
DEBUG: Browser sleep for 100ms
DEBUG: Taking full screenshot
DEBUG: Taking browser screenshot
DEBUG: No element provided, continue with full browser screenshot.
INFO: Reading ref image: NotFound
DEBUG: Reading ref image file: /workingdirectory/app/webapp/test/e2e/reference/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.ref.png
DEBUG: Comparing current screenshot to reference image: NotFound
DEBUG: Image comparison failed, reference image: NotFound, difference in percentages: 0.03% (threshold: 0.1%), difference in pixels: 671 (threshold: 50) ,update disabled
INFO: UI5 Version: 1.71.25
INFO: UI5 Timestamp: 202009081410
DEBUG: Storing ref,act and diff images: NotFound
DEBUG: Storing image file: /workingdirectory/app/webapp/test/e2e/target/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.act.png
DEBUG: Storing image file: /workingdirectory/app/webapp/test/e2e/target/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.diff.png
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-open-Not-Found-view_3_fail_2021-03-05T12-06-35.png"
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/test/utils/Component-preload.js - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/test/utils/Component-preload.js - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.075719 failed to load JavaScript resource: com/organisation/sapui5/app/test/utils/Component-preload.js -  sap.ui.ModuleSystem"
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/test/utils/i18n/i18n_en_US.properties - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/test/utils/i18n/i18n_en.properties - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/test/utils/i18n/i18n.properties - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 178:167 "could not find any translatable text for key 'appTitle' in bundle 'test/utils/i18n/i18n.properties'"
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 178:167 "could not find any translatable text for key 'appDescription' in bundle 'test/utils/i18n/i18n.properties'"
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/i18n/i18n_en_US.properties - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/i18n/i18n_en.properties - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 2206 Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 2206 Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 2206 Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 2206 Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/versionInfo/mta.json - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.414479 The following problem occurred: error - Not Found,404,Not Found "
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.414840 Loading of data failed: undefined -  "
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/versionInfo/package-lock-app.json - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.415370 The following problem occurred: error - Not Found,404,Not Found "
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.415580 Loading of data failed: undefined -  "
DEBUG: BROWSER LOG: SEVERE: http://localhost:5050/app/versionInfo/package-lock-srv.json - Failed to load resource: the server responded with a status of 404 (Not Found)
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.416054 The following problem occurred: error - Not Found,404,Not Found "
DEBUG: BROWSER LOG: SEVERE: https://sapui5.hana.ondemand.com/1.71.25/resources/sap-ui-core.js 171:722 "2021-03-05 13:06:26.416254 Loading of data failed: undefined -  "
INFO: Expectation FAILED: Image comparison failed, reference image: NotFound, difference in percentages: 0.03% (threshold: 0.1%), difference in pixels: 671 (threshold: 50) ,update disabled
INFO: Expectation FAILED details: {"refImageUrl":"/workingdirectory/app/webapp/test/e2e/reference/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.ref.png","actImageUrl":"/workingdirectory/app/webapp/test/e2e/target/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.act.png","diffImageUrl":"/workingdirectory/app/webapp/test/e2e/target/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/NotFound.diff.png"}
DEBUG: Expectation FAILED stack: Error: Failed expectation
    at expectVisualPage (/workingdirectory/app/webapp/test/e2e/specs/NotFound.spec.js:15:34)
    at UserContext.<anonymous> (/workingdirectory/app/webapp/test/e2e/specs/NotFound.spec.js:31:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
INFO: Spec finished: should open Not Found view with status: FAILED
INFO: Spec started: should navigate back to "my cases" view
DEBUG: Screenshot created "target/report/screenshots/click_container-app---notFound--notFoundMessagePage-navButton_0_2021-03-05T12-06-36.png"
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-navigate-back-to--my-cases--view_1_pass_2021-03-05T12-06-37.png"
DEBUG: Taking actual screenshot
DEBUG: Browser sleep for 100ms
DEBUG: Taking full screenshot
DEBUG: Taking browser screenshot
DEBUG: No element provided, continue with full browser screenshot.
INFO: Reading ref image: Home
DEBUG: Reading ref image file: /workingdirectory/app/webapp/test/e2e/reference/images/NotFound/mac/1600x1200/chrome/belize/ltr/cozy/Home.ref.png
DEBUG: Comparing current screenshot to reference image: Home
DEBUG: Image comparison passed, reference image: Home, difference in percentages: 0% (threshold: 0.1%), difference in pixels: 0 (threshold: 50)
DEBUG: Screenshot created "target/report/screenshots/NotFound-should-navigate-back-to--my-cases--view_2_pass_2021-03-05T12-06-39.png"
INFO: Spec finished: should navigate back to "my cases" view with status: PASSED
INFO: Suite finished: NotFound with status: FAILED for: 14.665s
INFO: Suite specs summary, total: 2, passed: 1, failed: 1, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 6, passed: 5, failed total: 1, failed with error: 0, failed with image comparison: 1
INFO: Overall status: FAILED for: 14.671s
INFO: Overall suites summary, total: 1, passed: 0, failed: 1
INFO: Overall specs summary, total: 2, passed: 1, failed: 1, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 6, passed: 5, failed total: 1, failed with error: 0, failed with image comparison: 1
[13:06:39] I/launcher - 0 instance(s) of WebDriver still running
[13:06:39] I/launcher - chrome #01 failed 1 test(s)
[13:06:39] I/launcher - overall: 1 failed spec(s)
DEBUG: Tearing down connection provider environment
[13:06:39] E/launcher - Process exited with error code 1`

**Comment by maximnaidenov** [comment]
So where is the problem, I do not see anything like" "Expectation FAILED: Expected " that you mention happens with 1.44.2 and upper ?

**Comment by ramondebeijer** [comment]
problem lies in the report.html if I open it i get a base64 encode string on the screen instead of the matched percentage and screenshots
![Schermafbeelding 2021-03-05 om 13 52 04](https://user-images.githubusercontent.com/11766455/110118193-45995d80-7dba-11eb-89e5-7486cd1e84c7.png)

**Comment by maximnaidenov** [comment]
the screenshot reporter that generates this html is not intended for the visual testing usecase and so it is possible that we broke it with some other feature. We will have a look and see if we can fix it.
For the visual testing we have the htmlReporter, it will show the actual and reference images correctly. Can you please try it and see if it fits your requirements ?

**Comment by tsaleksandrova** [comment]
or use the "visual" profile.. 
this special handling for toLookAs matcher is introduced in https://github.com/SAP/ui5-uiveri5/pull/180 .. seems like it wasn't tested thoroughly

**Comment by ramondebeijer** [comment]
@tsaleksandrova how do i set the visual profile?

**Comment by tsaleksandrova** [comment]
fixed in 1.46.3
