### ISSUE TITLE
Cannot use .asControl() on ElementFinder that is obtained by sap.m.Column control locator

### ISSUE THREAD

**Issue by ruzickam** [SAP/ui5-uiveri5#294]
Dear UIveri5 team,

I use following control locator to get all `sap.m.Column` controls:
`{ controlType: 'sap.m.Column', ancestor: { controlType: 'sap.m.Table', id: 'myTable' } }`

Then I tried to check the `importance` property of the first `sap.m.Column` control:
`expect(getAllColumnElements.get(0).asControl().getProperty('importance')).toBe('High');`

Unfortunately I got following error message in the console:

> INFO: Expectation FAILED: Failed: getControlProperty: Element with ID "" is not part of a control DOM representation tree

EDIT: It seems that `<div>` elements with no 'id' attribute are found by the `sap.m.Column` control locator.

Could you please have a look at this issue?

Best regards,
Michal

**Comment by maximnaidenov** [comment]
This sounds as trying to interact with non-rendered or non-visible table. Do you see this exact table rendered in the screenshot report ?. Please note that in UIVeri5, opposite to OPA, the interactable selector is off by default. So the by.control() will catch anything in the control tree (similar to by.css that will also catch invisible elements). So it will efectively "see" hidden tables like the ones in Nav containers. By the way, the Test Recorder will generate a correct selector, please give it a try.

**Comment by ruzickam** [comment]
Yes, the table is visible in the screenshot.

I found the cause of the issue. The ID is empty because wrong element is found:

![div_found_instead_of_th](https://user-images.githubusercontent.com/15248517/110622083-4a378a80-819b-11eb-8411-fb32488016e8.png)

**Comment by ruzickam** [comment]
I cannot reproduce the issue on this page with a basic `sap.m.Table`:
https://openui5.hana.ondemand.com/entity/sap.m.Table
(I did post a comment here before that it was possible, but I made a mistake, sorry about that)

The issue occurs only when a Smart Table is present above the `sap.m.Table`. For example the issue is reproducible here:
https://sapui5.hana.ondemand.com/1.87.0/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable.mtable

I used this code:
`const column = element(by.control({ controlType: 'sap.m.Column', id: '__table0-Bukrs', ancestor: { controlType: 'sap.m.Table', id: '__table0-ui5table' } }));`
`expect(column.asControl().getProperty('id')).toBe('__table0-Bukrs');`

and got the error again:
> INFO: Expectation FAILED: Failed: getControlProperty: Element with ID "" is not part of a control DOM representation tree

Wrong element is found by the locator above:
![div_found_instead_of_th](https://user-images.githubusercontent.com/15248517/110629941-0ea1be00-81a5-11eb-8b07-a26c6d17c6af.png)

**Comment by maximnaidenov** [comment]
Can you please send (in mail) a link to the app + credentials where we can reproduce the error ?

**Comment by ruzickam** [comment]
E-mail has been sent.

**Comment by tsaleksandrova** [comment]
in short, you should add `interaction: "root"` to the selector
the found element is the "focus dom ref" which is the first element that uiveri5 looks for (by default)
unfortunately it doesn't have an id, which breaks the reverse search (element->control->properties)
as a proper solution, we should change the controlfinder to also check for id

**Comment by tsaleksandrova** [comment]
we also fixed the problem (in UI5 - sap.ui.test._ControlFinder). you can try it in the nightly version:
https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable.mtable
