### ISSUE TITLE
Learning UIveri5

### ISSUE THREAD

**Issue by venkatui5** [SAP/ui5-uiveri5#297]
Hi All,

I am very new to UIveri5 . I want to learn UIveri5 tool for Fiori apps automation. Can any body guide me how to start the learning. Or  any tutorial/Documents. Please guide or share it with me.
Your response is very much appreciated.

Thanks & Regards,
venkat Rao

**Comment by maximnaidenov** [comment]
Hi, here is a list of some sources:

Our presentations at UICon2019, it includes an attractive live coding demo: https://www.youtube.com/watch?v=jlOUkRdNxO0

I would also say that the following Dev guide is also very good intro: https://developers.sap.com/tutorials/cp-cicd-sytem-test.html
Our TechEd 2020 hands-on session is also good way to get to know the tools: https://github.com/SAP-samples/teched2020-dev267
There is also a short intro of UIVeri5 in this openSAP course “Efficient DevOps with SAP”: https://open.sap.com/courses/devops1
 
I also suggest our blogs:
https://blogs.sap.com/2019/01/29/uiveri5-for-e2e-testing-of-ui5-apps/
https://blogs.sap.com/2020/01/23/test-recording-with-ui5-test-recorder/
https://blogs.sap.com/2020/11/30/yeoman-generators-for-opa5-and-uiveri5/
