### ISSUE TITLE
UI5 dependencies are not loaded on this page 

### ISSUE THREAD

**Issue by jiangxin0503** [SAP/ui5-uiveri5#301]
Hi guys,

We are using the UIVeri5, but it always  come out with the error: 
```
15:57:08 INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page

```

Our test config is to test the **specify** flp apps in CF with the baseURL:

```
exports.config = {
  baseUrl: 'https://****/cp.portal/site#apptest-display',
  directConnect: true,
  auth: {
    // form based
    'sapcloud-form': {
      user: 'ueser',
      pass: 'password',
      conditionalLogonButtonSelector: '#logOnFormSubmit',
    },
  },
```
You can see, we maintain the user and password to logon of the CF flp, after logon, the UIVeri5 is hanging until timeout.

with error:

```
15:57:08 INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
```

**Comment by maximnaidenov** [comment]
This typically happens when the auth was not successfull like wrong username/pass. I also see you have a condtionalLogin selector, are you sure you need this ?.
But the analisys should start by looking at the screenshot report and checking what really happens.

**Comment by maximnaidenov** [comment]
Closed due to inactivity

**Comment by MrNickell** [comment]
Hi Guys,

Here is the current error message:

`INFO: Expectation FAILED: Failed: Waiting to redirect to login page,
Wait timed out after 300003ms`

It occurs after we passed first testing spec ( which means the login action is OK when we execute the first spec ). And then when we execute the following specs, the redirect error occurs... 

After executing every spec,  we tried to run following codes to clear auth info
`afterAll(() => {
    browser.testrunner.config.auth = { plain: {} };
  });`
But the redirect error is still there.

**Comment by maximnaidenov** [comment]
@MrNickell 
It is bad idea to ask question on similar looking but actually unrelated question. Especially when they are closed.
You can set authOnce: true and the authentication will be executed only once. But take care for any inter-spec app state dependency.

**Comment by MrNickell** [comment]
@maximnaidenov 

Sorry for forgetting to explain that  I and **jiangxin0503** are now in the same development team, so now we are facing the issue in the same context... And I will try to use authOnce: true to see if it works.  Thanks!
