### ISSUE TITLE
How to pass authentication to browser locally

### ISSUE THREAD

**Issue by ZhanJohnny** [SAP/ui5-uiveri5#304]
Hi 
  
  We have a APP developed by CAP. there is authentication in backend. So when we access App locally, browser requests user/password as below ,  How to set default user/ password in Conf.js to fill this authentication form automatically ? 
I try to add below basic auth in conf.js  , but it doesn't work. 
auth: {
	basic: {
		user: "<user>",
		pass: "<pass>"
	}
}

![image](https://user-images.githubusercontent.com/50702068/114966788-e002bb80-9ea5-11eb-9d84-f38b7d13fe3d.png)

**Comment by maximnaidenov** [comment]
Using basic auth is especially bad idea and is strongly discouraged in SAP apps. Anyway, the basic auth as described here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md
If you face problems, please give some details.

**Comment by ZhanJohnny** [comment]
Hi @maximnaidenov ,

  Basic auth is just for local testing. I already checked the URL mentioned by you. Try to use basic auth to fill user/password automaticlly. but it failed. Which auth method is suitable for my case ?
attached my conf.js:
![image](https://user-images.githubusercontent.com/50702068/115000740-9d58d780-9ed5-11eb-8e15-59fc5d7e0d61.png)

**Comment by maximnaidenov** [comment]
Can you please describe your local case - what is protected, does the app handle anything and how is this supposed to work productively ?

**Comment by ZhanJohnny** [comment]
Hi @maximnaidenov ,

In my app, it uses XSUAA to authenticate user.  it is a fiorielement-based APP in fiori launchpad . During local uiveri5 testing, browser requests the user/password to continue.  I hope uiveri5 could fill the user/password automatically. How can i set the auth in conf.js ?

Thanks,
Johnny

**Comment by maximnaidenov** [comment]
Hi @ZhanJohnny,
actually nor UIVeri5, nor any other tool can interact with browser modal auth popup. This is not supported by selenium  and so we can't do it. So the only way is to make sure the dialog does not appear by providing the user and pass in the url as a URL basic auth that we support. But this also requires support from your server, serving the app.

**Comment by ZhanJohnny** [comment]
Hi @maximnaidenov ,
  
  Thanks a lot for your proactive response.  close this issue.
