### ISSUE TITLE
File Uploader Input not writing Input value

### ISSUE THREAD

**Issue by Masood10** [SAP/ui5-uiveri5#306]
I have a File Uploader and I am trying to send the path of my file to its input element but Its not entering any text in the input column. Manually when I click the input a file explorer is opened and I can attach my file. For testing purposes I am trying to send the file path to my input element using send keys

`    UploadInput.sendKeys(
      "/sadsad.csv"
    );`
I have created an absolute path as well as tried with simple strings but nothing is written. 

To select the element I have used the following code
`        UploadInput: element(
          by.control({
            controlType: "sap.m.Input",
            viewName: "MyViewName",
            ancestor: {
              id: "MyUploader",
              viewName: "MyViewName",
            },
          })
        ),`

and tried other options like 

`    element(by.control({
        id: "MyUploader",
        viewName: "MyViewName",
        interaction: {
            idSuffix: "fu"
        }
    })),`

No text is written in my input only a cursor is shown inside the input column. I have tried multiple things but not sure why it is still not working

**Comment by maximnaidenov** [comment]
Hi, can may have a look here:  https://github.com/SAP/ui5-uiveri5/issues/189

**Comment by Masood10** [comment]
Actually I started my implementation from #189  but it does not work for me. I have tried multiple solutions

**Comment by maximnaidenov** [comment]
Have you tried to identify the file input control with the test recorder:  https://blogs.sap.com/2020/01/23/test-recording-with-ui5-test-recorder/

**Comment by Masood10** [comment]
Yes I have used the test recorder to identify the input control using enter text
![image](https://user-images.githubusercontent.com/16192134/115390451-8ae4e380-a1de-11eb-9b40-356a3d39f90d.png)

**Comment by Masood10** [comment]
Thank you for your response. The problem was that my path that I was providing in the UploadInput.sendKeys( "/sadsad.csv" ); was not being resolved. I started testing with test string and thats an issue. We have to have a correct path with a file behind it otherwise no value will be shown
