### ISSUE TITLE
Scrolling issue in TreeTable

### ISSUE THREAD

**Issue by Rohit-Badugu** [SAP/ui5-uiveri5#307]
Hi,

We are facing an issue in writing a test for scrolling. The requirement for us is to write a UIVeri5 test for scrolling behavior in sap.ui.table.TreeTable.

Some of the options which we tried

1. Use of window.scrollTo() function. Since the TreeTable resides within the ObjectPage this didn't work for us.
2. Use of mouseMove() function. Since the TreeTable use virtual scrolling concept we are unable to trigger mouse move to element in second page.

Can you please suggest as to how we can resolve our issue. Let me know if you need more information.

Best Regards,
Rohit Badugu

**Comment by maximnaidenov** [comment]
Can you please give some more details - what is inside what and what exactly you want to scroll - the object page or the table ?. Screenshots of the initial and desired states would also help.

**Comment by Rohit-Badugu** [comment]
Hi, 

The TreeTable is within the ObjectPageSubSection control. At the start of app, 14 rows are shown in TreeTable. The requirement is to scroll TreeTable one page down and show next 14 rows. 

Initial State
![image](https://user-images.githubusercontent.com/42056317/115685858-3e341080-a376-11eb-846e-bccd637e3009.png)

After Scrolling 
The scrollbar should move to next page
![image](https://user-images.githubusercontent.com/42056317/115685928-5310a400-a376-11eb-83f8-13d643a941c1.png)


Thank you!
Rohit Badugu

**Comment by maximnaidenov** [comment]
Here is a snippet from an internal wiki with hints:
Scroll to button in ObjectPageLayout Header

Locate the ObjectPageLayout via viewName and controlType to retrieve its dynamic ID getProperty("id")
Send a javascript command to the browser to scroll to the ObjectPageLayout Header: 'sap.ui.getCore().byId("' + sId + '").getScrollDelegate().scrollTo(0,0)'
var HomeScreenNavigate = element(by.control({
   viewName:'ExtensibilityExplorer.view.ReadMoreOnExt',
   id:'navigateToHomepage'
}));

var objectPageLayout = element(by.control({
   viewName: "ExtensibilityExplorer.view.ReadMoreOnExt",
   controlType: "sap.uxap.ObjectPageLayout"
}));
...
iHomeNavClick: function () {
   var objectPageLayoutId = objectPageLayout.asControl().getProperty("id").then(function(sId) {
       browser.executeScript(
           'sap.ui.getCore().byId("' + sId + '").getScrollDelegate().scrollTo(0,0)'
       ).then(function () {
           HomeScreenNavigate.click();
       });
   });
},

The idea is to find an element that is visible and scroll it the top of the container. We plan to expose this idea as utility in UIVeri5 but did not reach this yet.

**Comment by Rohit-Badugu** [comment]
Hi,

The above approach worked for me. Thank you so much for you help. :)
I am closing the issue now.


Warm Regards,
Rohit Badugu
