### ISSUE TITLE
Xpath locators cannot be found for running Application in Cloud Foundry

### ISSUE THREAD

**Issue by Fielmann-Wei** [SAP/ui5-uiveri5#308]
Hi,

I have a Testscript using Uiveri5 for a Fiori Elements Application. The App was first deployed on an On premise Launchpad and we have deployed it now on the SAP Cloud Platform.
We have been using the Xpath Controllers because the other IDs did not always work. The testsrcipt works on the On Premise Solution but on the central Launchpad I receive the message, that "No element found using locator". I have checked the Xpath on SCP but it is the same. Other control IDs do also not work.

For SCP I only changed the authentication method to "sapcloud-form".

I am using the Chromedriver version: "89.0.4389.23" fixed in the config file.

What I figured out is that the app needs more time to get fully loaded in SCP. I therefore have increased tge timeouts in the spec file. I also have checked the method with "browser.driver.wait". But still uiveri5 cannot locate the Xpath Controller.

Thanks for any help.

**Comment by Fielmann-Wei** [comment]
Stacktrace:

`INFO: Opening: https://XXXX
[18768:3372:0425/120752.453:ERROR:device_event_log_impl.cc(214)] [12:07:52.453] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[18768:3372:0425/120752.486:ERROR:device_event_log_impl.cc(214)] [12:07:52.486] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[18768:3372:0425/120752.492:ERROR:device_event_log_impl.cc(214)] [12:07:52.492] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[18768:3372:0425/120752.516:ERROR:device_event_log_impl.cc(214)] [12:07:52.516] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
INFO: UI5 Version: 1.89.0
INFO: UI5 Timestamp: 202104210846
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
INFO: Expectation FAILED: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
INFO: Expectation FAILED: Failed: Waiting for page reload to finish
Wait timed out after 50000ms
INFO: Spec finished: Adding a Payment transaction with status: FAILED
INFO: Spec started: Deleting a Payment transaction
INFO: Expectation FAILED: Failed: No element found using locator: By(xpath, //*[@id='PaymentTransaction::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PAYMENTTRANSACTION--listReportFilter-filterItemControl_BASIC-CardNumber-inner'])
INFO: Spec finished: Deleting a Payment transaction with status: FAILED
INFO: Suite finished: Happy-Paths with status: FAILED for: 75.843s
INFO: Suite specs summary, total: 3, passed: 1, failed: 2, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 3, passed: 0, failed total: 3, failed with error: 3, failed with image comparison: 0
INFO: Overall status: FAILED for: 75.854s
INFO: Overall suites summary, total: 1, passed: 0, failed: 1
INFO: Overall specs summary, total: 3, passed: 1, failed: 2, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 3, passed: 0, failed total: 3, failed with error: 3, failed with image comparison: 0
[12:09:02] I/launcher - 0 instance(s) of WebDriver still running
[12:09:02] I/launcher - chrome #01 failed 2 test(s)
[12:09:02] I/launcher - overall: 2 failed spec(s)
[12:09:02] E/launcher - Process exited with error code 1`

**Comment by maximnaidenov** [comment]
Hi, what do you see in the screenshot report (target/schreenshots/report.html) ?

**Comment by Fielmann-Wei** [comment]
For the first testcase I see the page fully loaded and the error message:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\XXX\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

It is not even trying to find a locator.

The second testcase I see the page loaded and it cannot find the locator. NoSuchElementError: No element found using locator: By(xpath, //*[@id='PaymentTransaction::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PAYMENTTRANSACTION--listReportFilter-filterItemControl_BASIC-CardNumber-inner'])
    at

**Comment by maximnaidenov** [comment]
Can you please share the test script and the conf.js file. The message "Waiting for page reload to finish" is not part of UIVeri5 so seems you have some custom waiting ?

**Comment by Fielmann-Wei** [comment]
**conf.js:** 

`exports.config = {
  profile: "integration",


  //cloud URL
baseUrl: "XXX",
authOnce: true,
auth: {
  'sapcloud-form': {
     config: 'Form-Authenticator',
     idpSelector: 'a[href*="https://arqgyqmrp"]', //html atag
    //passFieldSelector: '#PASSWORD_FIELD-inner',
    //logonButtonSelector: '#LOGIN_LINK',
      user: 'XXX',
      pass: 'XXX',
  }
},
  connectionConfigs: {
    direct: {
        binaries: {
            chromedriver: {
                version: "89.0.4389.23"
            }
        }
    }
 },

 timeouts: {
  getPageTimeout: '50000',
  allScriptsTimeout: '11000',
  defaultTimeoutInterval: '30000'
},

};


and the **testcase**:

require("./pages/home");
require("./pages/generalInformation");

describe("Happy-Paths", function () {

  let Kartennummer = '000560398234-9000001800';
  let Vertriebsbelegnummer = '5603982';
  let Kartenart = 'xxx';
  let Datum ='18.03.2021';


   it("Adding a Payment transaction", function () {
    browser.driver.wait(function(){
      return browser.driver.findElements(by.id('#PaymentTransaction\:\:sap\.suite\.ui\.generic\.template\.ListReport\.view\.ListReport\:\:ZC_PAYMENTTRANSACTION--listReportFilter-btnGo')).then(function (elements) {
        //return !!elements.length;
      });
    }, //browser.getPageTimeout, 'Waiting for page reload to finish'
    );
      
    When.onTheHomePage.iCreate();
    debugger;
    When.onTheGeneralInformationPage.iEnterCardnumber(Kartennummer);
    When.onTheGeneralInformationPage.iEnterSalesDocumentNumber(Vertriebsbelegnummer);    
    When.onTheGeneralInformationPage.iEnterCardType(Kartenart);
    When.onTheGeneralInformationPage.iClickCreate();
    Then.onTheHomePage.iSeeGo();
    });

**Comment by maximnaidenov** [comment]
why do you need the browser.driver.wait statement ?
Also, please note the timeouts should be relative, please make sure allScriptsTimeout is larger than  getPageTimeout

**Comment by Fielmann-Wei** [comment]
At first I did neither use the browser.driver.wait statement nor the timeout statement. Somehow running the testscript in the Cloudfoundry it seemed that the initial loading of the app took quiet long due to loading many packages at low speed. The testscript without those two statements could not find the locator either and I was thinking that the initial loading of the app was the problem. 
Concluding me to put these two statements in the testcase in the first place.

**Comment by maximnaidenov** [comment]
Slow app would be fixes with extending the timeouts. Please remove this wait statement and please provide a new log.

**Comment by Fielmann-Wei** [comment]
Hi,

the new log shows: 

`INFO: @ui5/uiveri5 v1.46.2
INFO: Resolving specs
INFO: Found correct binary locally: C:\Users\xuwei\AppData\Roaming\npm\node_modules\@ui5\uiveri5\selenium\chromedriver-89.0.4389.23.exe
INFO: Executing 1 specs
[09:27:07] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"WINDOWS","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"count":1,"loggingPrefs":{"browser":"SEVERE"}}

DevTools listening on ws://127.0.0.1:51345/devtools/browser/a6dd536a-ebcc-45a6-ab4a-a011654c2932
INFO: Suite started: Happy-Paths
INFO: Spec started: Adding a Payment transaction
INFO: Opening: https://XXX
[5300:9756:0427/092709.508:ERROR:device_event_log_impl.cc(214)] [09:27:09.508] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[5300:9756:0427/092709.518:ERROR:device_event_log_impl.cc(214)] [09:27:09.518] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
INFO: UI5 Version: 1.89.0
INFO: UI5 Timestamp: 202104210846
INFO: Expectation FAILED: Failed: No element found using locator: By(xpath, //*[@id='PaymentTransaction::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PAYMENTTRANSACTION--addEntry'])
INFO: Spec finished: Adding a Payment transaction with status: FAILED
INFO: Spec started: Deleting a Payment transaction
INFO: Expectation FAILED: Failed: No element found using locator: By(xpath, //*[@id='PaymentTransaction::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PAYMENTTRANSACTION--listReportFilter-filterItemControl_BASIC-CardNumber-inner'])
INFO: Spec finished: Deleting a Payment transaction with status: FAILED
INFO: Suite finished: Happy-Paths with status: FAILED for: 25.941s
INFO: Suite specs summary, total: 3, passed: 1, failed: 2, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 2, passed: 0, failed total: 2, failed with error: 2, failed with image comparison: 0
INFO: Overall status: FAILED for: 25.947s
INFO: Overall suites summary, total: 1, passed: 0, failed: 1
INFO: Overall specs summary, total: 3, passed: 1, failed: 2, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 2, passed: 0, failed total: 2, failed with error: 2, failed with image comparison: 0
[09:27:34] I/launcher - 0 instance(s) of WebDriver still running
[09:27:34] I/launcher - chrome #01 failed 2 test(s)
[09:27:34] I/launcher - overall: 2 failed spec(s)
[09:27:34] E/launcher - Process exited with error code 1`

The Screenshot shows fully loaded apps. The Xpaths are still correct and the timeouts are:

 timeouts: {
  getPageTimeout: '50000',
  allScriptsTimeout: '110000',
  defaultTimeoutInterval: '30000'
},

**Comment by maximnaidenov** [comment]
Hi,again - the timeouts MUST be relative e.g. getPageTimeout < allScriptsTimeout < defaultTimeoutInterval. So please make sure defaultTimeoutInterval is like twice bigger than allScriptsTimeoout. Also please update to latest uiveri5, it is 1.46.3.
Also, please use the UI5 test recorder:https://blogs.sap.com/2020/01/23/test-recording-with-ui5-test-recorder/ to resolve selector of some element (for example the go button) and please put it as a first selector in the first it() block.

**Comment by Fielmann-Wei** [comment]
Hi,

thanks for the information. I have been using the search for element method of the Chrome Browser so far for that application as the SAPUI Version of the app is lower than 1.74 and therefore the testrecorder cannot be used. The Version of SAPUI should not have an issue with my selectors, I guess, since it works with the onpremise Launch pad. Or do I miss out any important informations? Should I upgrade the SAPUI Version just for the Testrecorder purposes?

**Comment by maximnaidenov** [comment]
Closing the ticket due to inactivity, please reopen if necessary. Do not forget to read my last request for logs and actual test script.
