### ISSUE TITLE
Unable to upload a file through fileUploader.

### ISSUE THREAD

**Issue by nuramon9999** [SAP/ui5-uiveri5#310]
Hi there :)
I have tried the approach on  #189, but sendKeys only goes into the input but is unable to type anything. When in the element I cannot type anything either. 
Could the input be disabled? If so, how to I reenable it.
Alternatively, I can change the value of the element. Then I can actually input something. But then I do not know how to submit the fileUploader.
Any advise on that? 
Best regards,
Pascal

_Originally posted by @nuramon9999 in https://github.com/SAP/ui5-uiveri5/issues/189#issuecomment-827453452_

**Comment by maximnaidenov** [comment]
File uploading is handled by webdriver, it recognises you are entering path into an input of type=file and actually uploads the file. So you only need to make sure you correctly target the proper element. Please have a look here:
https://github.com/SAP/ui5-uiveri5/issues/189
