### ISSUE TITLE
Access suiteFilter in config.js to change reporter file name

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/ui5-uiveri5#318]
Hi experts!

In my project, we use UIVeri5's `suiteFilter` to split long running tests (4 suites) in two (parallel) test stages in our CI/CD pipeline (with 2 suites each). However, we noticed that the JUnit files generated have the same name, regardless of the chosen `suiteFilter`, causing problems down the line as you can't distinguish the files from the outside.

In the short-term, it would be good to know if there is an easy way to access the `suiteFilter` in our `config.js`, either programmatically or via some template-mechanism (like with [authentication](https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md#authentication-configurations)), to be able to configure our reporters like this:

```js
  reporters: [
    {
      name: './reporter/junitReporter',
      reportName: 'target/report/UIVeri5-${suiteFilter}.xml',
    },
  ],
```

In the long run (but here I really don't know), it might even be useful to be able to configure UIVeri5 to generate different (uniquely named) XMLs for each suite (or spec, depending on config), which would then cover `suiteExclude` and their `spec*` counterparts as well.

Thank you very much for your support!
Kind regards
Lukas

**Comment by maximnaidenov** [comment]
Hi,

templating is generic e.g. everything in config object (result of conf.js merged with profiles) would be processed and be available for replacement. So suiteFilter placeholder replacement should work, have you tried it? 
Currently we work on "native" parallel execution and there we will need to solve this same problem. Our current approach (wip) is to merge the results of individual specs( executed in parallel sessions) onto a single report - screenshot, json, etc.

Regards,
Maxim

**Comment by LukasHeimann** [comment]
Uh, I wasn't aware it's generic, I thought this was a special case with authentication!

The only problem I could imagine is that we now might be the commas. We give `--suiteFilter=one,two`, which now results in a filename `target/report/UIVeri5-one,two.xml`. Surprisingly, this works fine on windows, but I'm not sure about the tooling in our pipeline. I guess we'll have to test this and see.

Thank you very much for your support and giving insights on the future plans!
