### ISSUE TITLE
How to check if atleast one spec failed

### ISSUE THREAD

**Issue by rishabh2408** [SAP/ui5-uiveri5#324]
Hi,

I want to run an **it** block only if there were no failures in any of the previous specs, is there any global variable that I can use to check the status?

Or some other way in which I can make sure my it block runs only if there were no failures before.

Best Regards,
Rishabh Jain

**Comment by rishabh2408** [comment]
Hi,

Any update on this?

**Comment by hmanchev** [comment]
HI Rishabh,

We are evaluating possible solution for you.

Please expect some delay due to vacations period.

BR,
Hristo

**Comment by maximnaidenov** [comment]
No, there is no such option, if an it() block fails, all subsequent ones will also run and most likely fail.

**Comment by rishabh2408** [comment]
Hi @maximnaidenov,

Is there a variable I can use within the **it** block in an if condition and decide what needs to be done?

Since in the logs we anyways get the status as failure and we also show the summarized suite results in the end with the total number of failures that means we store the number of failures somewhere. If I can check the value of that variable my purpose will be solved.

BR,
Rishabh

**Comment by maximnaidenov** [comment]
It is not that simple, all test frameworks that could handle async test, including jasmine use a process queue. So the it() blocks are executed synchronously but  only schedule their callbacks. What you can do it a to have a single it() and inside, as a last statement, conditionally call the subsequent it() e.g. schedule them dynamically. But this will make your test really hard to read. Or you can play around with jasmine internals and do some ifs but this is not something we could help you.
What you ask is a fail-fast feature and it is in our plans to work on it but I can't give you any estimation when we would reach it.
