### ISSUE TITLE
Latest chromedriver is forced without checking chrome version

### ISSUE THREAD

**Issue by dvc1201** [SAP/ui5-uiveri5#329]
Hi Colleagues,

- On a Jenkins test agent Chrome92 installed and an update for Chrome93 is not available yet. (Because of the region or central policies)
- UIVeri5 forces the latest Chromedriver93
- Chrome92 cannot work with ChromeDriver93
- In the Java package what we use to have the correct Chromedriver version in run-time the installed Chrome version is checked and the proper Chromedriver.exe is downloaded
- Is it possible to add similar feature to the UIVeri5?

Best regards
Peter Dobos

![image](https://user-images.githubusercontent.com/3524409/127493107-19babe27-ff25-43aa-a093-f403d6d570d2.png)

![image](https://user-images.githubusercontent.com/3524409/127492625-9402f587-61fe-4b2d-86f7-c6b8288ab63c.png)

**Comment by maximnaidenov** [comment]
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md
and even better approach:
https://blogs.sap.com/2020/12/01/ui5-testing-how-to-handle-chromedriver-update-in-docker-image/

**Comment by maximnaidenov** [comment]
There is no way to start chrome uniformly on different OSes, chromedriver handles the starting but only when opening a page and hense will crash on invalid version. We do not want to duplicate and support the logic that resolves the browser location so we can't start it preemptively and get the version.

**Comment by dvc1201** [comment]
Thanks Maxim. The blog helps to resolve the problem.

**Comment by dvc1201** [comment]
This issue can be closed from my side.
