### ISSUE TITLE
Unable to run my testcases on safari browser in mac in saucelab

### ISSUE THREAD

**Issue by riteshgetsetup** [SAP/ui5-uiveri5#331]
WebDriverException: Message: The command 'POST /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXX579CA406/timeouts/async_script' was not found.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'itako698.prod.miso', ip: 'fe80:0:0:0:1006:6c33:de0c:8b92%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '9.0.4'
Driver info: driver.version: unknown

can anyone help me please

**Comment by hmanchev** [comment]
Could you please share your conf.js file and how you call uiveri5?

**Comment by riteshgetsetup** [comment]
Thanks Hristo.

**Comment by riteshgetsetup** [comment]
*** Settings ***
Library    SeleniumLibrary    
   
*** Variables ***
${browser}     chrome
${url}  https://www.jio.com/
${userid}      amit@getjio.com
${password}    Work##58800
@{_tmp} 
    ...  browserName: chrome,
    ...  platform: macOS 11,
     ...  version: latest,
    ...  name: ${SUITE_NAME},
    ...  build: Web Testcases
   
 
${browsers}    chrome
${capabilities}     ${EMPTY.join(${_tmp})} 
${remote_url}     ***hide***    

*** Keywords ***


 TestCase01    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase02
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase03
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase04
    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase05
    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase06
    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase07
    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase08
    
    Open browser  ${url}  browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase09
    
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase10
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase11
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase12
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase13
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase14
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase15
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase16
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase17
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase18
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase19
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase20
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}
TestCase21
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}

TestCase22
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities} 

TestCase23
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}

TestCase24
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}    
TestCase25
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}  

TestCase26
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}   

TestCase27
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}    

TestCase28
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}  

TestCase29
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities} 

TestCase30
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}

TestCase31
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}   

TestCase32
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}

TestCase33
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}    

TestCase34
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}

TestCase35
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}   

TestCase36
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}      

TestCase37
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}     

TestCase38
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities} 

TestCase39
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities} 

TestCase40
    Open browser  ${url}     browser=${browsers}
    ...  remote_url=${remote_url}
    ...  desired_capabilities=${capabilities}     
   

*** Test Cases ***

TC01-Logged in with email id
 TestCase01
 #Title To verify the loggedin
     [TAGS]  Functional
     Maximize Browser Window
     Set Selenium Implicit Wait    2
     Wait Until Element Is Visible    xpath://*[@id="PopupSignupForm_0"]/div[2]/div[1]  
     Click Element     xpath://*[@id="PopupSignupForm_0"]/div[2]/div[1] 
     Click Element    //span[normalize-space()='Log in | Sign up']
     Click Element    //span[@class='highlight']  
     Input Text    //input[@type='email']   ${userid} 
     Click Element    //section[@class='login']//div//section//button[@type='submit']    
     Input Password   //input[@placeholder='Password']   ${password}
     Click Element    //div[@class='font-verdana mb-5']//div//button[@type='submit']
     Set Selenium Implicit Wait    3
     [Teardown]  Close Browser
           
     
TC02 Verify Login using valid email id and valid password
      TestCase02  
    [TAGS]  Functional  
     
     
     Maximize Browser Window
      Set Selenium Implicit Wait    5  
     #Wait Until Element Is Visible    xpath://*[@id="PopupSignupForm_0"]/div[2]/div[1]  
     Click Element     xpath://*[@id="PopupSignupForm_0"]/div[2]/div[1] 
     click element  xpath://span[normalize-space()='Log in | Sign up']
     Set Selenium Implicit Wait    5
     #click on I use email to login
     click element  xpath://span[@class='highlight']
     click element   xpath://section[@class='login']//div//section//button[@type='submit']
     Input Text    xpath://input[@type='email']   amit@getsetup
     click element   xpath://section[@class='login']//div//section//button[@type='submit']
     [Teardown]  Close Browser

**Comment by hmanchev** [comment]
I can't understand what you sent. 
Are you sure that you are using uiveri5 for automatic your test scenario?

If yes - please send me your conf.js file.

**Comment by riteshgetsetup** [comment]
i not created any config .js file & i am directly run the file for testcases

**Comment by hmanchev** [comment]
I can't imagine how you could start a test without conf.js file.
Are you using uiveri5?

**Comment by maximnaidenov** [comment]
In those logs I do not see a single line that is comint from UIVeri5 so obviously you are not using our framework . You understand we do not support ANY OTHER TEST FRAMEWORK !!!
