### ISSUE TITLE
Infobar messages are not being closed by UIVERI5

### ISSUE THREAD

**Issue by nair-sumesh** [SAP/ui5-uiveri5#333]
As per my observation, UIVERI5 handles the infobar messages, or popup message (automatically displayed at the time of login) and closes these popups before proceeding with test execution.
However, this is not happening for one case(see below snapshot) and due to this, the info message strip is restricting the controls behind the message strip to be controlled by UIVERI5.

![image](https://user-images.githubusercontent.com/12034160/128250539-b640db1d-b156-4284-ba08-ace9e6e91fde.png)

**Comment by hmanchev** [comment]
Hi,

This message bar is not from the browser but from the application.
If it hides some controls behind, you can close it first.

**Comment by nair-sumesh** [comment]
> 
> 
> Hi,
> 
> This message bar is not from the browser but from the application.
> If it hides some controls behind, you can close it first.

The infobar is from FLP  and appears on the home page and across all applications.

**Comment by maximnaidenov** [comment]
@nair-sumesh  So what do you expect us to do? UIVeri5 is test framework that enables you to write e2e tests for UI5 apps. We do not deal with FLP, S4 systems or anything like this.

**Comment by nair-sumesh** [comment]
Hi Maxim,

I was in an impression that UIVERI5 handles the popups (like co-pilot authentication screen). 
I observed this kind of handling in the past. 

Anyway, it seems that's not the case. I will try to handle the infobar messages in my test cases(and will have to do it for all the apps being tested). 
Thanks again.
