### ISSUE TITLE
Issue while launching the firefox browser using uiveri5

### ISSUE THREAD

**Issue by Saurabh-Silori** [SAP/ui5-uiveri5#337]
INFO: Check for latest version of: geckodriver.exe from: http://github.com/mozilla/geckodriver/releases/latest
INFO: Found latest version of geckodriver.exe: v0.29.1
INFO: Downloading webdriver binary: http://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.zip
INFO: Executing 1 specs
[10:13:01] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"firefox","platform":"WINDOWS","count":1,"loggingPrefs":{"browser":"SEVERE"}}
[10:13:01] E/launcher - Expected browser binary location, but unable to find binary in default location, no 
'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by hmanchev** [comment]
Hi, currently UiVeri5 doesn't support local execution against Firefox. It is due to Firefox droppped the support of JWP and allows only W3C protocol, which is still not implemented in UiVeri5. 

A workaround would be using some browser cloud (like SauceLabs) which provide some kind of retrofit API.
