### ISSUE TITLE
getTitle is not working as property for uiveri5 code

### ISSUE THREAD

**Issue by Saurabh-Silori** [SAP/ui5-uiveri5#338]
I have a piece of code which generated via Test recorder for uiveri5. I am using same through VScode and running. It is not running for control with properties as title. 

For eg : there is a code which clicks on Submit button. Code generated via test recorder or selected by me for attributes and title 

 var submitButton  = element(by.control( { properties:[{ title : "Submit" }] }));

This does not work via VSCode but through test recorder replay functionality it works.

when given as below in VSCode it works.

var submitButton = element(by.control( { controlType : "sap.m.Button", id : "__xmlview0--btnSubmit" }));

Question :
Why in test recorder i was given title option when I do not see title property in UI5 elements list using Devtools. Attached is the screenshot of Submit button.
![submit button UI5](https://user-images.githubusercontent.com/73687425/131968141-e4be76bc-747b-4cad-93e2-c74c76211e9f.PNG)

**Comment by maximnaidenov** [comment]
What do you see when you move your sight to the right , in the Properties panel of the Test Recorder ?

**Comment by Saurabh-Silori** [comment]
I think you are talking about this.. this comes by default, i changed criteria from Metadata to Attributes and then subcriteria to text . Attched is by default properties

![ByDefaultPropertiesforSubmit](https://user-images.githubusercontent.com/73687425/131972256-92e26a4a-9249-463a-975e-54ad66e83fb8.PNG)

**Comment by maximnaidenov** [comment]
What you show is a "UI5 Test Recorder" chrome extension that is not created or supported by SAP. So I could not comment what it shows and why.
What I mean for UI5 Test recorder is a build-in in UI5: https://blogs.sap.com/2020/01/23/test-recording-with-ui5-test-recorder/
