### ISSUE TITLE
Information regarding OPA5 and Uiveri5

### ISSUE THREAD

**Issue by Saurabh-Silori** [SAP/ui5-uiveri5#341]
I need to understand few things related to OPA5 and Uiveri5 

There are few limitations related to OPA5 could you plz help in understanding.Testing across more than one page : does that mean you cannot navigate to other page in UI5 application and it only supports single page of application. Could you help here
Screen capturing :We cannot capture screen in case of failure and report in results ?
authentication issues and fragility of test data : what does fragility means ?

UIVeri5 is said to be a system test tool. We have a scenario where data is embedded in UI5 application using SFTP and then validated and sent to S/4 HANA. Will UIVeri5 be able to automate such kind of scenarios or this tool is only meant for UI5 specific applications ?

Also we want data to either fetch from excel files or DB , does uiveri5 has some library or in built functions for same ?

**Comment by maximnaidenov** [comment]
Hi,
SPA (SinglePageApplication) is a javascript application that runs completely in the browser e.g. the javascript code is loaded and runs in the browser and renders UI elements. But the key point is that the page is never reloaded. This is the standard way to write UI5 applications. A single UI5 app could have many views and display many "pages". You could even navigate among many Fiori applications in a single FLP. But you can not navigate to app on another server or using another UI technology.

Screen capturing is a feature of the runner. The currently available OPA5 Karma runner does not support screenshot on error.

OPA test is executed completely in the browser and expects all backend calls to be mocked. This is required because it can't handle the authentication that is typically required by the backend.

UIVeri5 is a system and scenario testing framework for UI5 apps. The scenario you explain seems pretty complicated and I do not think UIVeri5 is the best tool for it.

**Comment by Saurabh-Silori** [comment]
Thanks Maxim for the prompt reply. Do we have something where we connect uiveri5 with database OR uiveri5 with excel file any utility or something. If not do we have to code using Excel Javascript API ?

**Comment by maximnaidenov** [comment]
Hi,
UIVeri5 is a testing framework for UI5 apps that enable you to CODE the test. And it handles only the interaction with UI5 UIs. This is not a fully-functional testing solution like Triscentis to example.  I really suggest that for cross-app business scenarios you should consider more complete tool.

**Comment by Saurabh-Silori** [comment]
I understand this as a tool centric for ui5 applications. My question here is as there are multiple fields on UI5 application and giving static input in code as hardcode is not a feasible approach in any framework so we take data from excel or csv files. Use that data to drive the scripts. Do we have anything that sort of ?

**Comment by maximnaidenov** [comment]
No, we do not have any excel or cvs file reading out of the box.

**Comment by Saurabh-Silori** [comment]
Hi Maxim, I have a question related to OKta authentication. We will be implementing okta dual factor authentication(ADS server and mobile) on our applications in future, as we know it cannot be automated. Usually we create a mocksession api to login into application to perform functional testing automation. Does uiveri5 and OPA5 support this or api's can be integrated in same ?

**Comment by maximnaidenov** [comment]
Will repeat again - uiveri5 is just a nodejs program, think of it as an API to control the browser. You can do whatever else you want by coding a nodejs program and executing as part of the test. 
That said, messing up with authentication, especially in the browser runtime is very, very tricky job. Additionally, I am not aware what exactly you mean by a mocksession token so can't comment on this very specific case.

**Comment by Saurabh-Silori** [comment]
Hi Maxim, yes you are correct we can code anything using node.js programming.

**Comment by Saurabh-Silori** [comment]
Yes Maxim, we can do stuff with Node.js and work.  Mocksession is just an api which creates session token and we can login in application easily. I will explore same from node.js side for uiveri5 however wanted to know if in OPA5 framework can we call an api ?

**Comment by maximnaidenov** [comment]
You can call any API from OPA5 but you can't control an app on another origin. E.e if you load the test from localhost, you can't control UI on myapp.hana.ondemand.com because this would violate the cross-rigin browser policy.

**Comment by Saurabh-Silori** [comment]
correct, we cannot call any other application api.. i want to call same domain api within opa5. i wanted to understand is there any code or something through which i can call an api(when i say call i mean to say just like we have restassured for api testing ) An example in selenium where we extract the response of api
URL url = new URL("https://it.intranet.com/service/v1/mockSession");
			Response strresponse = given().relaxedHTTPSValidation().baseUri().when().get().then().extract().response();
			//Response strresponse = given().baseUri().when().get().then().extract().response();
			cookieID= strresponse.getCookie("JWT_SESSION");
			Logs.info("cookie ID is:"+ cookieID);

**Comment by maximnaidenov** [comment]
Calling same domain API should be fine
