### ISSUE TITLE
Run function before any spec gets executed

### ISSUE THREAD

**Issue by simonegaffurini** [SAP/ui5-uiveri5#343]
Hi, is there a way to run a function before any spec test gets executed.
I'm looking for something like onPrepare available on Protractor config file.
I already tried putting the onPrepare like I would do with Protractor but it gets ignored by UiVeri5.

**Comment by maximnaidenov** [comment]
We do no support onPrepare. You can use beforeAll() and it will be called after the specs are loaded but before they are executed.

**Comment by simonegaffurini** [comment]
Hi thank you for your reply.
Yes, I could use beforeAll() however at that point the browser is already open.
I actually need to run some code that changes my baseUrl and I was looking for a way to avoid browser.get().
May I ask why there is no support for such function?

**Comment by maximnaidenov** [comment]
You can very easy disable the declarative authentication by setting baseUrl: null. Then you can do whatever you want in beforeAll and when ready, just call browser.go(<url?,auth)
