### ISSUE TITLE
authentication Issue in sapcloud-form

### ISSUE THREAD

**Issue by Mohithraj916** [SAP/ui5-uiveri5#345]
Hi,
Since there is change in SAP Cloud Form login (attached screenshot). Authentication is not working.
![image](https://user-images.githubusercontent.com/36323835/133602303-1f4b60ab-dc2b-44b2-ac2f-5f2c5c2454b9.png)
Getting this Error:

![image](https://user-images.githubusercontent.com/36323835/133602649-d2f98877-0360-4608-bf96-6e8f049b33f4.png)

It's it not able for find the password element, earlier both email and password field are in same authentication form. There is a continue button to work on action after entering email, anything. Any solution to fix it? Please Help

**Comment by maximnaidenov** [comment]
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md -> conditionalLogonButtonSelector
