### ISSUE TITLE
Uiveri5 Authentication

### ISSUE THREAD

**Issue by saurabhsilori** [SAP/ui5-uiveri5#347]
Hi Team,

I am using SAP Cloud for deploying applications in Cloud foundry. We have an authentication page asking for username first followed by login page(username and password). We went through the authentication doc, identified that if page has both username and password on same page then things work. Could you please let us know how to automate this type of authentication.
![SAP CF login](https://user-images.githubusercontent.com/51262409/135089832-1d3732f5-80f2-4bb5-ad12-4a82c197cd19.PNG)

**Comment by maximnaidenov** [comment]
This is a recent change in some landscapes (NEO ?) where the conditional login as this feature is called was enabled.
In UIVeri5 auth setup, we support it for quite some time: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md -> conditionalLogonButtonSelector
