### ISSUE TITLE
.sendKeys doesn’t work when executed in Jenkins pipeline but works fine locally.

### ISSUE THREAD

**Issue by robertiqkkk** [SAP/ui5-uiveri5#351]
Hello **UIVERI5** team, hope you are doing fine!

We are facing a strange issue - `.sendKeys` used to simulate file upload doesn’t work in Jenkins’ pipeline. 
But works completely fine locally. 

Before creating this issue, we’ve tried several things:

- Suggestions from this issue (https://github.com/SAP/ui5-uiveri5/issues/189)
  - Different ways to target DOM `<input type=”file”`
- Separate tests to define whether uiveri5 detects the `sap.ui.unified.FileUploader` itself. They are passing, which means that most likely the issue is `.sendKeys`
- Different ways to define a complete path to the file. But all of them are pointing to the same folder. Again made us think .sendKeys the one to blame
  - `__dirname`
  - `process.cwd()`
  - `path.resolve()`
  - `process.env.PWD`
- Different versions of **chromedriver**
  - Generally, we use the latest one but tried to manually set different versions via **CLI** parameter / as a part of **conf.js** configurations
- Different versions of **uiveri5** lib
  - Tried to set different versions manually to match the local setup

Since it’s working locally and not in Jenkins there should be some deviation in configuration, but we are struggling to detect it. 
Could you give us a hint of what might be wrong? 

BR, 
Robert

**Comment by hmanchev** [comment]
Hi Robert, 

It would be great if you share with us more details:
1. What you mean that is not working on Jenkins? Some expectation fails or you are receiving error? 
2. Share a snippet of how you are trying to upload file and how you are validating it.

Best Regards,
Hristo

**Comment by robertiqkkk** [comment]
Hello Hristo,

Thanks for the fast response!
The Mentioned [solution](https://stackoverflow.com/questions/34215697/remote-file-upload-protractor-test) did help us.

I've done only 2 changes to our spec.js:
- imported **_selenium-webdriver/remote_**
- added `setFileDetector` inside `beforeEach`.

```
const remote = require('selenium-webdriver/remote');

describe('MySpec', function () {
    
    beforeEach(function () {
        browser.setFileDetector(new remote.FileDetector());
    });
});
```

BR,
Robert
