### ISSUE TITLE
Programmaticaly disable declarative auth for a spec/suite

### ISSUE THREAD

**Issue by astarovojtov** [SAP/ui5-uiveri5#353]
Hello

Are there any options to switch off declarative authorization before running one spec/suite and turn back on for other?
Something like `beforeLaunch` hook in Protractor? 

We need to create a test with 2 different users and setting `baseUrl=null` in config for every spec is not the best option. 
Tried to set baseUrl to null in spec file before the test. Didn't work.

**Comment by hmanchev** [comment]
Hi Andrei,

The declarative auth is just a helper and there is not such possibility to turn on and off for different specs. 
If you want to achieve this, you might turn off the declarative auth and to use "programatic" auth in the beggining of each spec which requires auth. 

Best Regards,
Hristo

**Comment by astarovojtov** [comment]
Hello Hristo,

Using programmatic auth in the beginning of each spec is not the perfect solution for us, unfortunately :)
Thank you for clarification!
