### ISSUE TITLE
Timeout Issue when running uiveri5 script

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAP/ui5-uiveri5#357]
Hello Team,

We are facing the below Time out issue when we run our uiveri5 script. We run the script on a linux system through Jenkins.
```
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
INFO: Expectation FAILED: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
The same script was running successfully till last week so not sure why this error is displayed now. 

Files:
[conf.js](https://github.tools.sap/BTP-E2EScenarioValidation/MDO_UI/blob/master/conf.js)
[mdoui.spec.js](https://github.tools.sap/BTP-E2EScenarioValidation/MDO_UI/blob/master/mdoui.spec.js)

**Comment by hmanchev** [comment]
Hi Priyanka,

It is extremely bad idea to add explicit waits (browser.sleep) in your test! 
One of the main advanteges of UiVeri5 is the automatic synchronization with the application. 

These explicit waits are probably the reason for your timeout.
Please get rid of all explicit waits and avoid interacting directly to browser object and API.

You can inspire for some best practices from this tutorial: https://developers.sap.com/tutorials/cp-uiveri5-cap.html

I am closing this issue as your case (with explicit waits) is not supported in UiVeri5.
