### ISSUE TITLE
uiveri5 job in Jenkins fails

### ISSUE THREAD

**Issue by alikgarai** [SAP/ui5-uiveri5#365]
Hello Team,

I am facing one weird issue, where the uiveri5 tests run successfully locally, but when I run on the Jenkins, it fails. 
And every time it fails for different steps (not consistently failing for one particular step). I have also attached the last 3 test report in the github repo as mentioned below. 

Following is the snippet for one such error in Jenkins
![image](https://user-images.githubusercontent.com/24291750/151530913-aeb1eb7a-eff0-484c-8b6f-70030759e18a.png)

I use control locators with the help of ui5 test recorder tool.

Reference: https://github.tools.sap/I332308/cias-uiveri5

Thank you,
Alik

**Comment by hmanchev** [comment]
Hi Alik,

In the logs you provided I can see that the element is found but is not visible. This can be caused by smaller browser window in your Jenkins execution. The tests can pass locally with bigger browser window as all used elements are visible, but with smaller, they can be hidden (overflow).

In order to be able to further help you, I will need more details about the failure you are receiving. For example screenshot report?
Other useful detail would be how you are running the UIveri5 tests in Jenkins - headless browser, browser cloud, Piper step?

Best Regards,
Hristo

**Comment by alikgarai** [comment]
Hi Hristo,

Thanks for the quick reply. I have attached the last 3 screenshot reports in this [github link](https://github.tools.sap/I332308/cias-uiveri5/tree/master/reports).

In Jenkins, we pull the repo, navigate to the uiveri5 test directory and execute the uiveri5 command, as shown below:
![image](https://user-images.githubusercontent.com/24291750/151741821-7cb9ecc7-6257-48c2-93f0-0e073d5fc30e.png)

In the conf file, I didn't specify any browsers, as default is chrome.

Let me know if you need more details or we can even connect over a short call.

Thanks,
Alik

**Comment by alikgarai** [comment]
Hi Hristo,

I have attached the zip now, with the screenshots. [Link](https://github.tools.sap/I332308/cias-uiveri5/tree/master/reports)

I tried the following approaches to increase the browser size:

- using CLI command: uiveri5 --browsers=chrome::::1920x1080
- In the conf file,
    
![image](https://user-images.githubusercontent.com/24291750/152136941-b123074c-35bb-49dd-a037-e6935142e85a.png)

The issue still persist.

**Comment by hmanchev** [comment]
Hi Alik, 

It seems your configuration is not working as expected. The screenshots you sent are with lower resolution: 1024 × 652.
The conf you provided - you can't use maximized: true with combination of browserSize. With this conf the browser will just be maximized to the screen, so if your screen is smaller, you will never get the required browser size. 

If you are running on headless chrome, please specify it: $ uiveri5 --browsers=chromeHeadless
then remove maximized: true and keep only the browserSize.

Could you please share more details about your Jenkins setup? 
Are you executing on headless Chrome? 
Is it local on the Jenkins executor or remote? 

Best Regards,
Hristo

**Comment by alikgarai** [comment]
Thank you, Hristo, it worked. 

The jenkins job runs on a remote server and I am using headless mode. This is the latest conf which is running fine with full resolution.

![image](https://user-images.githubusercontent.com/24291750/153418186-e468bb13-c393-4791-8448-199d7ea92fa2.png)

However, sometimes the Jenkins fails and the screenshot reveals that the page was not completely loaded. Does it mean that I should add explicit wait time for the controls to load properly. I believe uiveri5 takes care of app rendering automatically.

**Comment by hmanchev** [comment]
Hi Alik,

Is this still relevant?

**Comment by alikgarai** [comment]
Hi Hristo,

It is resolved, will close the issue.

Thank you,
Alik
