### ISSUE TITLE
SAP Logon with Universal ID asks for Google Captcha

### ISSUE THREAD

**Issue by Nina-kora** [SAP/ui5-uiveri5#374]
For the tests with uiveri5 we created a separate SAP user. Now, after switching to SAP Universal ID, SAP login requires answering Google Captchas. What is the recommended way to work with SAP Universal ID in uiveri5?

**Comment by hmanchev** [comment]
Hello, 

Sorry for my late response. 
There is no solution for Google Captcha and/or SAP Universal ID. 

Basically the recommended appraoch is to have separeted authenticator for each method. As UIVeri5 is already deprecated, I don't think it's worth it to plan such implementation. 

I would recommend to consider migration to other E2E framework. Good alternative is wdi5: https://ui5-community.github.io/wdi5/#/

**Comment by maximnaidenov** [comment]
Hi,
as you know, the captcha is specially intended to disable "robots" e.g. exactly what you are trying to do. There is no framework that can do this and the only and correct way is to use a specially requested service user.

**Comment by Tian-Sebas** [comment]
Hi,
is there a way to disable the reCaptcha only for individual users? I assume this user would then have to be requested/authorized by SAP. I have already asked this question to SAP, unfortunately without an answer so far.

**Comment by maximnaidenov** [comment]
Hi, even if there is, this should be done by the IDP provider, the testing tool can't change how the login page works. As mentioned, the ONLY correct way is to request and use service user, specially created for this testing activity.
