### ISSUE TITLE
Tests do not launch with latest Chrome version 116

### ISSUE THREAD

**Issue by artembannikov** [SAP/ui5-uiveri5#381]
Hello,

I'm trying to run UIVeri5 tests from my local machine in a non-headless mode and the tests fail to launch due to the fact that as the latest release for chromedriver the version 114.0.5735.90 is downloaded:
```
INFO: @ui5/uiveri5 v1.47.9
INFO: Resolving specs
INFO: Check for latest version of: chromedriver.exe from: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
INFO: Found latest version of chromedriver.exe: 114.0.5735.90
INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
```

But this version of chromedriver can run only with browser version 114, while I have already Chrome being updated to version 116.0.5845.111:
```
[10:20:53] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Windows NT 10.0.22621 x86_64)
```

Any feedback on this issue will be appreciated.

uiveri5 version: v1.47.9
node version: v18.16.1
npm version: 9.8.1
system: Windows 11

**Comment by artembannikov** [comment]
Hello Hristo,

thank you very much for the quick reply. All clear! The workaround works well.
With that I'm closing the issue.

Best regards,
Artem

**Comment by luizcarlospedrosogomes** [comment]
Something that was reported 2 years ago and SAP has not yet resolved. This repository has been discontinued?

**Comment by hmanchev** [comment]
Hello, the project is deprecated around 3 years ago. It is stated at the top of the [README.md](https://github.com/SAP/ui5-uiveri5/blob/master/README.md)

There is a workaround for this issue, so if someone is still not migrated to another testing framework, can use it till the migration.
It is not recommended to use UIVeri5 for your tests scripts, as we cannot guarantee neighter support nor development/fixes.

Please consider migration to another testing framework. Good choice would be [wdi5](https://github.com/ui5-community/wdi5)
