### ISSUE TITLE
Latest UIveri5 version does not refer to latest chrome driver version

### ISSUE THREAD

**Issue by Priyadarshini-Ashokan-SAP** [SAP/ui5-uiveri5#382]
Hi

I am facing the following error after upgrading chrome to 116.x. It seems like the latest UIveri5 version still refers to 114 version of the chrome driver.

`INFO: @ui5/uiveri5 v1.47.9
INFO: Resolving specs
INFO: Check for latest version of: chromedriver from: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
INFO: Found latest version of chromedriver: 114.0.5735.90
INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip
INFO: Executing 1 specs
[14:04:26] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"LINUX","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars","start-maximized"]},"count":1,"loggingPrefs":{"browser":"SEVERE"}}
[14:04:34] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Mac OS X 13.5.0 arm64)
[14:04:34] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome`

Not sure if this is due to the changes in the chromedriver versions API - https://chromedriver.chromium.org/downloads/version-selection#h.4wiyvw42q63v

However this needs to be addressed ASAP, as this is breaking execution of tests.

**Comment by hmanchev** [comment]
Hello, 

The same issue is already discussed and I described workaround in #381 
Please refer to the solution there. 

Best Regards,
Hristo
