### ISSUE TITLE
version of ChromeDriver only supports Chrome version 114 but my local chrome version is 118

### ISSUE THREAD

**Issue by leonzhan** [SAP/ui5-uiveri5#384]
session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 118.0.5993.70 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Mac OS X 14.0.0 arm64)

I have tried upgrade webdriver-manager but it does not work for me

**Comment by hmanchev** [comment]
Hello, 

Please take a look at the pinned issue: https://github.com/SAP/ui5-uiveri5/issues/381
A workaround is described there
