### ISSUE TITLE
Provide a base class for Page Objects

### ISSUE THREAD

**Issue by fatschi** [SAP/ui5-uiveri5#57]
Hello Maxim,

as in OPA5 I would like to have the possibility to e.g. merge standard actions into my PageObjects via 'baseClass'. What do you think?

`
return Opa5.createPageObjects({
		onThePageXYZ: {
			baseClass: CommonPage,
			actions: {
				iPressTheUserButton: function () {
					const ...
`

**Comment by maximnaidenov** [comment]
Hi Fabian,
What would be the value of such base class ?. Now you could implement the same pattern by extending the individual objects of actions and assertions.

**Comment by fatschi** [comment]
Hello Maxim,
it would merge the arrangements, actions and assertions from the provided base object. See https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/test/PageObjectFactory.js for comparisson. The manual merge of the objects is much more boiler plate code in each page object, IMHO. I will provide a PR with a draft commit soon.

**Comment by tsaleksandrova** [comment]
Hi Fabian,
the main idea of the baseClass in opa is to 'inherit' the viewname, namespace and page object name. there aren't such things in uiveri5 atm. to me it makes more sense to have 'common' arrangements, actions and assertions - similar to those passed to Opa5.extendConfig

**Comment by maximnaidenov** [comment]
Closing as we have a PR for this: https://github.com/SAP/ui5-uiveri5/pull/59
