### ISSUE TITLE
geckodriver is fetching from wrong location

### ISSUE THREAD

**Issue by saard** [SAP/ui5-uiveri5#62]
HI,

When trying to override geckodriver the URL trying to be downloaded is:
http://github.com/mozilla/geckodriver/releases/download/0.19.1/geckodriver-0.19.1-linux64.tar.gz
Which receives 404.
The correct URL is:
https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz

basically they added "v" before version.

**Comment by maximnaidenov** [comment]
Hi saard,
what exactly is the problem you see ?.
The geckodriver versions have always been prefixed with 'v' but this doesn't matter as we resolve the 'latest' over the url redirection with latestVersionUrlRedirect. I just tested and it works fine:

INFO: Check for latest version of: geckodriver
(node:1807) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found latest webdriver version: v0.24.0
INFO: Downloading webdriver binary: http://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz
INFO: Executing 1 specs

Of course, you can override the 'latest' resolving by specifying an exact version and the version string should include the 'v'. See the drivers.md for sample how to set connectionConfigs setting.

**Comment by saard** [comment]
Hi Maxim,
Thanks for the response, I think I have figured it out.
I wanted to override the version since our docker is using firefox 57 which is compatible with geckodriver 0.19.1.
I guess I need to write down in the value v0.19.1 as the version name itself is prefixed with "v".

**Comment by saard** [comment]
Hi Maxim,

Thanks for the response, I understand now that I must include the "v" in my string.
