### ISSUE TITLE
aggregationLengthEquals matcher doesn't work

### ISSUE THREAD

**Issue by vobu** [SAP/ui5-uiveri5#69]
Hi,

it seems that the "aggregationLengthEquals"-matcher re-used from OPA5 doesn't work in the uiveri5-context.
I have prepared a running sample + corresponding test over at https://github.com/vobu/ui5-uiveri5/tree/bug/aggregationLengthEquals, this is the diff:
https://github.com/vobu/ui5-uiveri5/commit/d1b16c6a9dd74b0f6dd6adcc5877650f6c9e242c

The test fails with:
```
uiveri5 console: DEBUG: No elements found using by.control locator. This is what control locator last logged: Found control with the global ID 'ListPage1' -  sap.ui.test.Opa5
1 out of 1 controls met the matchers pipeline requirements -  sap.ui.test.pipelines.MatcherPipeline
Control 'Element sap.m.List#ListPage1' has 3 Objects in the aggregation 'items' but it should have undefined -  sap.ui.test.matchers.AggregationLengthEquals
0 out of 1 controls met the matchers pipeline requirements -  sap.ui.test.pipelines.MatcherPipeline

uiveri5 console: INFO: Expectation FAILED: Failed: No element found using locator: by.control({"id":"ListPage1","aggregationLengthEquals":{"name":"items","value":3}})
```

**Comment by maximnaidenov** [comment]
Hi Volker, thanks for reporting, we will have a look. 
I am wondering thy would you need to use this matcher at all ?. We were wondering if we need to expose it as it is leftover from OPA times before the autoWaiter was implemented. It was intended as kind of sync mechanism - like "wait till table gets populated". But in uiveri5, where sync is enabled by default, you could simply get the table length?

**Comment by vobu** [comment]
Hi Maxim,
the rationale behind using the `aggregationLengthEquals`is that from my understanding, it's only possible to obtain controls' properties via
```js
element(by.control({
  // ...
})).asControl().getProperty('...')
```
but not their aggregations like
```js
// pseudo-syntax
element(by.control({
  id: 'myTable'
})).asControl().getItems() // or .getAggregation('items')
```
So AFAIK, there's no other way to check for aggregations state and quality than using the `aggregationLength*` matchers such as
```js
element(by.control({
      id: "myTable",
      aggregationLengthEquals: {
        name: "items",
        value: 3
      }
    });
element(by.control({
      id: "myTable",
      	aggregationFilled: {
	  name: 'items'
	}
    })
```

Or am I missing something?

**Comment by maximnaidenov** [comment]
Seems we have missed this usecase ( aggregations length ). What do you think of an API like .getItems() that would return {length: X} ?

**Comment by maximnaidenov** [comment]
actually getAggregation('items')

**Comment by tsaleksandrova** [comment]
Hi Volker,
Did you try replacing the property 'value' with 'length'? The properties should be the same as for  https://openui5.hana.ondemand.com/#/api/sap.ui.test.matchers.AggregationLengthEquals; there is an error in locators.md

**Comment by maximnaidenov** [comment]
one idea to assert the length of aggregation is to find all entries with a more generic selector like element(<by table root>).element(by.control({controlType: 'sap.m.Item')) and then call the count() method.

**Comment by vobu** [comment]
> one idea to assert the length of aggregation is to find all entries with a more generic selector like element(by.control({id: 'myDropdown').element(by.control({controlType: 'sap.m.Item')) and then call the count() method.

yeah, sure, but what if you don't know (and don't care about :) ) the types the aggregation's items are of? 
That's why `aggregationLengthEquals` is so useful: change the `sap.m.List`'s aggregation items from `StandardListItem` to `sap.m.CustomListItem` and the test will be agnostic to that. (now of course you could argue that testing for the type of the items is important too, but let's not get too religious here :) )

**Comment by vobu** [comment]
> Hi Volker,
> Did you try replacing the property 'value' with 'length'? The properties should be the same as for https://openui5.hana.ondemand.com/#/api/sap.ui.test.matchers.AggregationLengthEquals; there is an error in locators.md

wow, that did the trick!
🎉 
~~value~~ -> length


I updated the ***test*** and ***locators.md*** in the fork-branch.
Do you want it as a PR? It would fix the docs, add a test cass and extend coverage while not changing any `uiveri5` behavior

**Comment by tsaleksandrova** [comment]
certainly👍 
thank you!

**Comment by vobu** [comment]
done: https://github.com/SAP/ui5-uiveri5/pull/70
also closing this
