### ISSUE TITLE
Defining test suites

### ISSUE THREAD

**Issue by HeneryHawk** [SAP/ui5-uiveri5#72]
Hi,
are there any plans to implement support for test suites like[ protractor](https://www.protractortest.org/#/page-objects) or selenium does?

I would like to separate my tests into various test suites so that i can execute particular tests behind a suite via cli parameter.

Regards
Simon

**Comment by maximnaidenov** [comment]
Hi,
we plan to implement support for explicit testsuite filtering, we have backlog for this but have some more stuff to complete before coming to this.
In the meantime, you could use several approaches to achieve the same:
1. Use single spec.js and include ( conditionally --params.key=value) subsets of the tests.
2. Use several conf.js files where you define specific suites with specs: '../smoke/*.spec.js'
and then call with uiveri5 smoke.conf.js

**Comment by maximnaidenov** [comment]
Closing as this is a feature request, already covered by our backlog.

**Comment by ThomasMarz** [comment]
Hello Maxim,

where is your backlog? I checked the TODO but this seems out of date:
https://github.com/SAP/ui5-uiveri5/blob/master/docs/todo.md

i tried to achieve 1. but do not understand how to read the params.key in my conf.js. Can you provide more info on this?

regards Thomas

**Comment by maximnaidenov** [comment]
Hi,
just updated the roadmap. Can you please open a new issue with details what you do and what error you get ?

**Comment by tsaleksandrova** [comment]
Hi again,
Here is a solution we plan to merge: #149
If you're interested, you could try it out and see if it fits your needs
Feedback is appreciated!
