### ISSUE TITLE
browserVersion does not work

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#74]
I have this issue.
![image](https://user-images.githubusercontent.com/2463861/58321236-eb661d00-7e1d-11e9-80d5-14e2e3ae7259.png)

So I tried to set the browserversion 73, but it has no effect.
`exports.config = {
    profile: 'integration',
    browsers:[{
        browserName: 'chrome',
        browserVersion: 73
      }],
    baseUrl: 'https://...index.html',
  };`

How can I configure the browserVersion?

**Comment by maximnaidenov** [comment]
Hi Manh,
what exactly do you want to achieve this way ?. You realize that uiveri5 won't upgrade or downgrade the already existing chrome on your system?

**Comment by impnguyen** [comment]
Hi, 
I expected that it will downloads the given chrome webdriver by the given browserVersion. In case of our company constraints, we do not have the latest chrome version. If I monitor the target path on filesystem, it always downloads the latest webdriver for chrome. 

I also tried this: 

`$ uiveri5 --config.connectionConfigs.direct.binaries.chromedriver.localPath=C:/chromedriver.exe
`

How can I achive to download a specific chrome webdriver?

**Comment by maximnaidenov** [comment]
Hi,
this particular field is intended for selenium hub scenarios where you have a number of nodes with different parameters - OS type, browser type, browser versions. For standalone scenarios where uiveri5 starts the browser, this field doesn't have any effect. 
To override the chromedriver version, please have a look here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md

**Comment by maximnaidenov** [comment]
We will discuss if we can consider the browserVersion when downloading the chromedriver, seems an interesting idea on first look.

**Comment by maximnaidenov** [comment]
Closing as took out to be a feature request.
