### ISSUE TITLE
Rich Text Editor can not display base64 image

### ISSUE THREAD

**Issue by AisonBird** [SAP/ui5-uiveri5#75]
while create an image with base64 src, and give it to Rich Text Editor. There was nothing ...
how to show the image in Rich text editor?
check my following code

// controller
var template = {};
var image ="<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAA...\"></img>";
template.body = image;
var oViewModel = new JSONModel(template);
this.getView().setModel(oViewModel, "template");
//view
<rte:RichTextEditor id="rte" value="{template>/body}" editorType="TinyMCE4" customToolbar="true" showGroupFont="true" showGroupInsert="true"
								showGroupLink="true" height="360px"/>

//inspector
an empty img element.
![image](https://user-images.githubusercontent.com/12046098/58448068-3becbb80-8139-11e9-9b2a-997c86efa406.png)

//version 
1.52.20

**Comment by maximnaidenov** [comment]
This is the issue tracker of uiveri5 where we support e2e tests. No idea how to work with this specific control.
