### ISSUE TITLE
Firefox driver download error

### ISSUE THREAD

**Issue by sirirao88** [SAP/ui5-uiveri5#78]
Hi UIVeri5 Team,

I just started creating my first test with uiveri5 and try to launch my application using Firefox. But I am getting the below error.

INFO: @ui5/uiveri5 v1.37.0
INFO: Resolving specs
INFO: Check for latest major version of: geckodriver.exe
INFO: Check for latest version of: geckodriver.exe
(node:4904) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found latest version of geckodriver.exe: v0.24.0
INFO: Downloading webdriver binary: http://github.com/mozilla/geckodriver/releases/download/v0.24.0-win32.zip
**Error: Error while processing: C:/Users/srao/AppData/Roaming/npm/node_modules/@ui5/uiveri5/selenium/geckodriver-v0.24.0.exe.zip ,details: Invalid or unsupported zip format. No END header found**
    at WriteStream.<anonymous> (C:\Users\srao\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\connection\directConnectionProvider.js:262:22)
    at WriteStream.emit (events.js:182:13)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:264:3)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Can you please help me to resolve this issue?
Thanks.

**Comment by tsaleksandrova** [comment]
Hi,
the download URL isn't correct, I tried it locally with default settings and my URL is correct: http://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-win32.zip
could you check your configuration for any custom changes?

**Comment by maximnaidenov** [comment]
I am closing this as it seems to be a configuration issue on your side. Please reopen if you have any other issue with geckodriver downlood.
