### ISSUE TITLE
OPA5 and UIVERI5

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-uiveri5#79]
Hi team,
could you explain more detailed which scenarios should be tested with OPA5 and when uiveri5 is the better choice?
Best Regards,
Florian

**Comment by maximnaidenov** [comment]
Hi Florian,
here you can find an overview of uiveri5 that covers exactly this distinction:
https://blogs.sap.com/2019/01/29/uiveri5-for-e2e-testing-of-ui5-apps/

**Comment by maximnaidenov** [comment]
Hi Florian, 
I am closing this issue, please reopen if you have further question on OPA vs UIVeri5

**Comment by flovogt** [comment]
@maximnaidenov Thanks a lot for clarification.
