### ISSUE TITLE
auth parameter access

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#82]
Hi, 

related to this `uiveri5 --params.user=<user> --params.pass=<pass>
` I would like to access the credentials. 

Inside the conf.js script I can access the params like this. 
`auth: {

  // form based
  'fiori-form': {
    user: '${params.user}',
    pass: '${params.pass}'
  }
}
`
In my login page object I can't do this. Do you have a public api documentation how I can access this cli arguments?

thanks in advance

**Comment by maximnaidenov** [comment]
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/parameters.md
