### ISSUE TITLE
UIVeri5 in AzureDevops

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#84]
I'm trying to use my working config (running on local machine) on Azure Devops Pipeline. 
This error occurs. 

![image](https://user-images.githubusercontent.com/2463861/58802137-af486e80-860c-11e9-9fd2-ec0eebf30ec0.png)

The pipeline installs the package.json and it runs in headless mode. 

`cd conf`

`
node ../node_modules/@ui5/uiveri5/bin/uiveri5 --params.user=$(username)--params.pass=$(password) --browsers=chromeHeadless
`

Do I have to do something additionally?

**Comment by maximnaidenov** [comment]
Hi Manh, 
you need to have the chrome browser installed in this machine/docker.

**Comment by luizcarlospedrosogomes** [comment]
@impnguyen did you manage to assemble your pipeline?
how was it?
