### ISSUE TITLE
has no dom representation

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#86]
I tried to access a input control, but I'll get this error message (but I can access Selects, TextAreas and Datepickers easily): 

![image](https://user-images.githubusercontent.com/2463861/59270412-b0534e80-8c51-11e9-9d8d-25bdd1d6d0fa.png)

My selector: 
`   
module.exports = {
... ProjKaEstimatedCosts: element(by.control({
        viewName: 'lew.ka.create_ka.view.projKa.CreateProjKa',
        // id: 'inputSchaetzkosten',
        controlType:'sap.m.Input',
        // interaction: "auto"
    })), 
...
}
 `

I also tried the idSuffix property: 
`interaction: {idSuffix: "vhi"}`

How can I access a input control to set a value?

**Comment by maximnaidenov** [comment]
This was an issue in some old UI5 versions what we fixed year ago. Which version of UI5 do you use ?

**Comment by impnguyen** [comment]
It is
![image](https://user-images.githubusercontent.com/2463861/59271241-b2b6a800-8c53-11e9-9c9c-8fc54a2f1a35.png)

**Comment by tsaleksandrova** [comment]
please try the same selector with `interaction: “focus"`

**Comment by impnguyen** [comment]
results:

- in Version 1.60.7 it works if I provide the interaction attribute via focus. Thanks to @tsaleksandrova 
- in Version 1.60.14 I also have to set the focus value for interaction attribute

**Comment by maximnaidenov** [comment]
The interaction: focus is only a workaround, it should work without it and I am sure we fixed in some version.

**Comment by maximnaidenov** [comment]
Seems we fixed this in 1.63.
