### ISSUE TITLE
exclude specs

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#89]
In protractor you can exclude specs by defining an array of specs in conf.js
https://stackoverflow.com/questions/32247255/protractor-how-to-exclude-spec-file-in-the-config-file
(but this does not work in uiveri5)

In uiveri5 I could only find the cli:
![image](https://user-images.githubusercontent.com/2463861/59508573-b98d2700-8eae-11e9-8c41-c8e5f3bac2a0.png)

How can I achieve a exclusion by conf.js?

thanks in advance

**Comment by maximnaidenov** [comment]
Hi,
every argument that you provide as arg, merges over the config object that you export from conf.js. So just add specExclude there and it will be used, of course, you could override from console args.

**Comment by ThomasMarz** [comment]
yes thanks Maxim, this worked for me:
uiveri5 --config.specExclude=print

unfortunately it does not work for "specFilter". Any clue?
