### ISSUE TITLE
Select from drop down

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#90]
Hi,

Is there any example available to select an element from drop down. Please refer to the screenshot
<img width="1680" alt="Screen Shot 2019-06-17 at 5 09 42 PM" src="https://user-images.githubusercontent.com/6157690/59601792-b7cb9980-9122-11e9-9348-5c92d907d700.png">
 for the type of drop down.

**Comment by impnguyen** [comment]
You could work with the element.sendKeys() method. 
`    MyObject.DropDown.sendKeys(protractor.Key.ARROW_DOWN);
`
Repeat sendKeys method n times and select the target entry by following
`    MyObject.DropDown.sendKeys(protractor.Key.ENTER);
`

**Comment by tsaleksandrova** [comment]
Hi,
first find the combobox and then find the child Item by its 'key' property. use a similar approach to what is described [here](https://openui5.hana.ondemand.com/#/topic/8615a0b9088645ae936dbb8bbce5d01d) in chapter 'Choosing an Item from sap.m.Select'

**Comment by nipun0212** [comment]
Thanks @impnguyen the solution worked.

**Comment by nipun0212** [comment]
Hi @tsaleksandrova,

Can you please give an example of the same. I am unable to modify the OPA code into uiveri5.

With Regards,
Nipun

**Comment by maximnaidenov** [comment]
Hi Nipun,

you should first find the dropdown and click it like:
var dropdown = element(by.control({id:"yourDropdown"}))
downdown.click();
and then you would find the item that you want (and belongs to this dropdown) and click it:
var item = dropdown.element(by.control({controlType:"sap.ui.core.Item",properties:{text:"ItemText"}});
item.click();
I am coding live here in the comment so please check the exact syntax in the docs.
