### ISSUE TITLE
get parent

### ISSUE THREAD

**Issue by impnguyen** [SAP/ui5-uiveri5#92]
Is there a possiblity to access the parent control with the "by.control" mechanism instead of using by.jq( ... :has...)?

https://github.com/SAP/ui5-uiveri5/blob/579da778e6885c2862b50b47001f743896cd5c8e/docs/usage/locators.md#select-an-element-that-contains-a-specific-child

**Comment by maximnaidenov** [comment]
Hi Mahn,

the by.control is a API over control, do not forget that the test runs in node runtime where as controls are living in the browser runtime. We want to keep the API thin so we promote "work as user" way to code the tests. So no, there is no straightforward way to get and interact the parent with .asControl() if thats what you want.
If you mean "descendant matcher" as in OPA: https://openui5nightly.hana.ondemand.com/#/api/sap.ui.test.matchers.Descendant, we plan to make it available in uiveri5 soon.
Or maybe you mean the "Ancestor" matcher in OPA ?. We have it implemented in protractor way like:
element.all().element(). Please see our docs for details.

**Comment by impnguyen** [comment]
"descendant matcher" seems to be the way I'm searching. So I will wait. 

Thanks in advance.
