### ISSUE TITLE
driver is always downloaded, even if it already exists locally

### ISSUE THREAD

**Issue by raeckesoft** [SAP/ui5-uiveri5#99]
the error is a problem in case the current user has no write access to the global npm folder

directConnectionProvider.js

  return that._getLatestVersion(binary).then(function () {
    return that._checkIfBinaryExists(binary.executable, true).then(function () {
      return that._downloadDriver(binary);
    });
  });

**Comment by maximnaidenov** [comment]
Thanks for reporting this, we will merge the fix shortly.

**Comment by tsaleksandrova** [comment]
solved with #100
